### PR TITLE
fix monitor delete race

### LINKED ISSUE #338: AttributeError: monitor with tqdm_notebook
I'm seeing this after the last batch of an interator:

```
/mnt/data2/anaconda3/envs/pytorch/lib/python3.5/site-packages/tqdm/_tqdm_notebook.py in __iter__(self, *args, **kwargs)
    185     def __iter__(self, *args, **kwargs):
    186         try:
--> 187             for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
    188                 # return super(tqdm...) will not catch exception
    189                 yield obj

/mnt/data2/anaconda3/envs/pytorch/lib/python3.5/site-packages/tqdm/_tqdm.py in __iter__(self)
    899             self.n = n
    900             self.miniters = miniters
--> 901             self.close()
    902 
    903     def update(self, n=1):

/mnt/data2/anaconda3/envs/pytorch/lib/python3.5/site-packages/tqdm/_tqdm_notebook.py in close(self, *args, **kwargs)
    203 
    204     def close(self, *args, **kwargs):
--> 205         super(tqdm_notebook, self).close(*args, **kwargs)
    206         # If it was not run in a notebook, sp is not assigned, check for it
    207         if hasattr(self, 'sp'):

/mnt/data2/anaconda3/envs/pytorch/lib/python3.5/site-packages/tqdm/_tqdm.py in close(self)
   1000         # decrement instance pos and remove from internal set
   1001         pos = self.pos
-> 1002         self._decr_instances(self)
   1003 
   1004         # GUI mode

/mnt/data2/anaconda3/envs/pytorch/lib/python3.5/site-packages/tqdm/_tqdm.py in _decr_instances(cls, instance)
    410             if not cls._instances and cls.monitor:
    411                 cls.monitor.exit()
--> 412                 del cls.monitor
    413                 cls.monitor = None
    414         except KeyError:

AttributeError: monitor
```

### PR DESCRIPTION
**Pull request by casperdcl**
attempt to fix #338

### CODE REVIEW

**Comment by casperdcl** [comment]
@elbamos could you try out this branch and confirm it fixes your problem?

**Comment by elbamos** [comment]
@casperdcl Yes, it does fix that issue.  What I'm seeing now is that the progress bars look odd, although I can't tell if that's because of this change or something in my code.

**Comment by lrq3000** [comment]
Thanks Casper yes this fixes the issue but I would like to know why, because normally it should not happen. I can see only two possibilities: either cls.monitor never gets initiated in user's code, or cls.monitor.exit() deletes the attribute cls.monitor (but I can't see how that is even possible). In both cases, we should do another fix somewhere else.

@elbamos can you please provide a code snippet that reproduces this error?

**Comment by elbamos** [comment]
Unfortunately I've overwritten the notebook that was doing this.

I can tell you that the way the code worked, it simply passed an iterator to create the tqdm_notebook object. This is then passed to the routine engine.train() in package torchnet (pytorch/tnt on github). Then on each epoch, a hook is called that updates the desc attribute of the iterator.

**Comment by lrq3000** [comment]
@elbamos ah it's a shame, well we're going to fix this issue like this for the moment. I guess anyway it's not critical, since it's at the moment when the monitor should be deleted, it should not impact the rest of tqdm anway.

@casperdcl I validated the PR, it can be merged :)

**Comment by casperdcl** [comment]
@lrq3000 I label things `bug-critical` if `tqdm` could cause a program to crash. So this is kind of critical. I assume it happens if two threads get into the delete block (`if not cls._instances and cls.monitor`) at the same time.

**Pull request merged**
