### PR TITLE
Pythonic submodules architecture

### LINKED ISSUE #176: should not import optional dependencies until actually necessary
while troubleshooting some awkward side effect of my app failing as far as I import tqdm, I discovered that tqdm unconditionally imports ipython (and probably other functionality if present, such as pandas) even if I have no intent on using it.  It adds quite quite an overhead to the import, e.g.

with ipython installed/available
```shell
buildbot@922f7d817f64:~/build-custom$ time python -c 'import tqdm'

real    0m0.194s
user    0m0.168s
sys     0m0.020s
```

without:
```shell
(venv-ci) buildbot@922f7d817f64:~/build-custom$ time python -c 'import tqdm'

real    0m0.057s
user    0m0.040s
sys     0m0.012s
```
i.e. having ipython available contributes now almost 300% penalty
I guess ideally all those imports should happen only if related functionality is requested

### PR DESCRIPTION
**Pull request by lrq3000**
Should fix #176, #245 and the second issue in #188 by reorganizing tqdm modules with a more pythonic architecture. This will allow a small performance boost (for all modules including core) as noted in https://github.com/tqdm/tqdm/pull/258#issuecomment-245119167.

The main goal of reorganizing tqdm's modules architecture is to avoid unnecessary imports without relying on delayed imports nor wrappers (which bring a whole lot of other issues, like no help message in IPython or other interpreters and the inability to call class methods such as `tqdm_notebook.write()`).

The minor goal is to take this reorganization opportunity to enhance the overall API (uniformization for example, but if you have other ideas/complaints, please shout out in the discussion!).

Basically, I implemented the architecture suggested by @wernight:
- each module is now exposed publicly (eg, `_tqdm_notebook.py` -> `notebook.py`):

```
# Before:
from tqdm import tqdm_gui
# Now:
from tqdm.gui import tqdm
```
- submodules import and declaration in `__all__` were removed from `__init__.py`
- all classes are now named `tqdm()` and `trange()`, this uniformizes the usage of `tqdm` across all modules. For example, it will ease the end-user implementation of adapting import codes.
  Before:

```
if ipython_notebook:
    from tqdm import tqdm_notebook as tqdm
    from tqdm import tnrange as trange
else:
    from tqdm import tqdm, trange

for element in tqdm(some_iterator):
    pass
```

Now:

```
if ipython_notebook:
    from tqdm.notebook import tqdm, trange
else:
    from tqdm.core import tqdm, trange
```

Note that I don't consider this change mandatory, but I wanted to profit of the opportunity that we are anyway changing the library architecture to see if API uniformization could be done. I am very open to feedback about this.
- `__init__.py` still imports and expose `tqdm.core` as the default tqdm, so the old API for the core module is still compatible:

```
# Both are equivalent
from tqdm import tqdm, trange
from tqdm.core import tqdm, trange
```

This also implies that `tqdm.core` is always imported even if the user only uses a submodule such as `tqdm.gui`, but since anyway all current submodules subclass from `tqdm.core`, this doesn't change anything (and anyway importing `tqdm.core` is not really heavy since it doesn't rely on any third party module...).

Do you find this new architecture and API easier to use? Any feedback is welcome! (Users are also welcome to participate!)

TODO:
- [ ] Update README
- [ ] Write in CONTRIBUTION the smooth rolling scheme (and modules acceptance guidelines) as described in #252.
- [ ] Write list of submodules with their status in README.
- [ ] Test `examples/` scripts.

### CODE REVIEW

**Comment by lrq3000** [comment]
A very interesting slides presentation about successful APIs such as request:

https://speakerdeck.com/kennethreitz/python-for-humans

We indeed keep the API as the most important objective of `tqdm` since it's clearly this "feature" that greatly helped in the currently widespread adoption. Then I guess performance of the core `tqdm` should be the second priority, then simple/elegant code (for maintenance), and then the rest.

All that is to say that if anybody has any idea on how to further enhance the `tqdm` API, please speak now!

**Comment by lrq3000** [comment]
Talking about API, here's a maybe interesting module to generate documentation (but it seems like it's reinventing the wheel, can't see the difference with doxygen...):
https://github.com/BurntSushi/pdoc

**Comment by CrazyPython** [comment]
@lrq3000 

- I strongly want `tqdm` to have some PEP 484 type stubs. They help your editor/linter out *a lot*.
- We should seriously have a "Performance Fest" where we try to inch that `80ns` to something more like `70ns`. 
- We should have a `tqdm_bare_bones` with only bare bones features for speed.

**Comment by lrq3000** [comment]
About `tqdm_bare_bones`, there is a stripped down version retaining the most important features of `tqdm` in the perf test:

https://github.com/tqdm/tqdm/blob/50fc2d85eab1cb35ca8cf67ac49e97528d2afcf7/tqdm/tests/tests_perf.py#L91

It's currently used only for the perf test to ensure that core `tqdm` does not get slower than **2 times** the bare bone version, so `tqdm` is still pretty efficient given all the features that are currently implemented! So yeah, we can easily put it in a separate submodule if asked.

**Comment by lrq3000** [comment]
[Type hints are very cool](https://docs.python.org/3/library/typing.html), this brings pure Python closer to Cython and Julia, but it's unfortunately only available for Python >= 3.5.2 right now. Maybe it will be backported to Python 2 in the future? Also, we would have to ponder whether the added verbosity (and thus code obfuscation) is worth the tradeoff (for the moment, typing is not really useful in Python but I guess it will be in the future for performance optimizers such as PyPy).

**Comment by CrazyPython** [comment]
@lrq3000 As I said, include **stub files**. You can provide `*.pyi` files of the same name as the executable files. Python 2 ignores stub files and it's part of the official standard.

**Comment by lrq3000** [comment]
Ah great! I didn't see that separate stub files were possible (I thought they were talking about stub like in the sense of unit tests). About PyPy and Cython not using type hints, yes I just saw that [here](https://blog.jetbrains.com/pycharm/2015/11/python-3-5-type-hinting-in-pycharm-5/) :(

Ok great, so here is the provisional TODO list to implement type hinting in `tqdm`:

- [ ] Implement type hint .piy stub files ([tutorial here](https://blog.jetbrains.com/pycharm/2015/11/python-3-5-type-hinting-in-pycharm-5/) and [autogeneration tools here](http://stackoverflow.com/questions/35602541/create-pyi-files-automatically)).
- [ ] Test statically using MyPy?
- [ ] Add MyPy static test to Makefile
- [ ] Automate MyPy test in Travis

**Comment by lrq3000** [comment]
I tried to install and use `mypy` on Windows and on Python 2.7, and it's not working. I don't know if this is a bug in the current version, but there is no mention in the documentation that stubs are supported in Python 2, only comment-based syntax (see [here](http://mypy.readthedocs.io/en/latest/faq.html#how-do-i-type-check-my-python-2-code) and [here](http://mypy.readthedocs.io/en/latest/python2.html)).

So for the moment I'll drop this until it matures a bit more. Because I can't implement something that I cannot test.

**Comment by CrazyPython** [comment]
@lrq3000 try on Unix? Are you using Cygwin? and get a $5 raspberry pi for testing (raspian preinstalled), python isn't that great with windows

**Comment by CrazyPython** [comment]
@lrq3000 It may be a pain, but it really does help my editor a lot. Seriously, I type annotate every function I write, and I won't be using the code in a week.

It's already a stable feature, and don't worry about incompatibility: you can just delete the `.pyi` files if they don't work.

Do it! I'm tempted to open a PR just for this! One time I even wrote a wrapper just for the type annotations for a library function.

**Comment by lrq3000** [comment]
Given the new insight about the performance impact of the current architecture of ```__init__.py``` (which would be alleviated by the new pythonic architecture), I would like to push this PR further and merge it ASAP @casperdcl you are OK with that. Retrocompatibility with core tqdm is assured, only the API for submodules will change.

Hopefully, I would like to push before the end of September this PR as v5.0 along with #250, #257 (and maybe #244 if OK for you Casper) and include new submodules in alpha stage as #248, #258. We should leave #251 (monitoring thread) and other PRs for later.

**Comment by lrq3000** [comment]
About #258 maybe not now, in fact it's almost ready, we just have to choose whether we keep functional tqdm_bare or class-based tqdm_bare_class, and then just copy some unit tests. So if it can be done for v5.0 that would be great but if not ready we'll leave it for later. I think this PR is of utmost importance, we should not move forward with new submodules until we have merged this PR.

**Comment by CrazyPython** [comment]
@lrq3000 this is quite old already

**Comment by lrq3000** [comment]
Yes but it's a major change to the API, it's normal that it takes time. But I don't want to go further without @casperdcl 's approval, I think we should both agree when we do any change to the API architecture.

**Comment by casperdcl** [comment]
Oh hello. Since filtering all tqdm emails I haven't been up to date with this. What's the order of things you'd like reviewed/merged, @lrq3000 ?

1. #198
2. #250
3. #257
4. #244
5. #248

**Comment by lrq3000** [comment]
@casperdcl The opposite, #198 should be last (because else we will have to recode manually the other PRs I think). I can manually redo #198 once the others are merged.

**Comment by lrq3000** [comment]
@casperdcl Except #198 that should be last, the order is correct.

**Comment by lrq3000** [comment]
When renaming and moving files around, this can be useful so that submodules PR don't have to be reworked:

* http://stackoverflow.com/a/5487775/1121352
* https://www.patrick-wied.at/blog/rename-files-and-folders-with-git

**Comment by lrq3000** [comment]
Rebased on master and did it in a cleaner fashion (using `git mv`), so this PR should be easily rebasable on newer commits if needed.

@casperdcl I'm done here but I need your opinion on the renaming of tqdm classes, because it's up to us: it was suggested that all submodules should contain `tqdm()` and `trange()` class/func, so that we can do:

```
from tqdm.core import tqdm, trange
from tqdm.gui import tqdm, trange
from tqdm.notebook import tqdm, trange
```

Etc... You see the pattern (the only exception being `tqdm_pandas` which is a monkeypatch wrapper so its usage will be `from tqdm.pandas import tqdm_pandas`).

But we can also keep the old naming scheme:

```
from tqdm.core import tqdm, trange
from tqdm.gui import tqdm_gui, tgrange
from tqdm.notebook import tqdm_notebook, tnrange
# etc...
```

But remember there is nothing in ```__init__.py``` anymore specifying how to find the subclasses.

I implemented the first approach (renamed the subclasses) in this PR. What do you think about it?

**Comment by lrq3000** [comment]
@casperdcl I'd really like to target mid-december for the next major release with the new submodule architecture and the ready to merge experimental submodules, because I think during christmas we'll have a lot of new users and feedback and so it's a good timeframe opportunity for the project (because more features = wider audience). I won't be available much (similar to currently, I can only review and comment) until the beginning of december, but then I will be to merge all of these.

**Comment by lrq3000** [comment]
@casperdcl Also can I ask you why you didn't review my PRs yet? I mean we don't need to merge them right now (anyway I can't), and you can add a message to your review to tell me to delay, but you can review a few PRs from time to time instead of planning to do the review of all of them in a batch later, don't you think? If it's just because you are short on time then no problem, but if there is something bothering you about the PRs please tell me.

**Comment by casperdcl** [comment]
Hi @lrq3000 , I've looked at open PRs with the label to-review. do tag others if they're ready for review. time is ... precious... yes.

**Comment by lrq3000** [comment]
Ok i will, thanks for the reviews Casper :)
Le 12 Nov. 2016 17:26, "Casper da Costa-Luis" <notifications@github.com> a
écrit :

**Comment by lrq3000** [comment]
@casperdcl Thank you very much for the work you did this week-end, that's perfect. All the milestone v5.0 tagged PRs are indeed the one I planned to be merged. I added a few more that I will rewrite or finish by next month, so we should be able to meet the deadline and have the new modular architecture. I will tag the submodules to be merged later for milestone >5.

**Comment by casperdcl** [comment]
bon, merçi Stephen.

**Comment by casperdcl** [comment]
Ah such love backlog much is. note to self: add things like `TqdmUpTo` from https://github.com/tqdm/tqdm#hooks-and-callbacks` to external submodules...

**Comment by casperdcl** [comment]
also TODO: make things like #482, #494 easier (direct access to variable dictionary rather than having to parse bar strings in a custom stream)

**Comment by casperdcl** [comment]
proposed submodule structure:

- `core`
  + `tqdm(class)`, `trange()`
- `tqdm = core.tqdm`, `trange = core.trange`
- `notebook`
  1. `tqdm(class)`, `trange()`? Prefer this.
  2. Or `tqdm_notebook(class)`, `tnrange()`?
  3. Or combo?
- `gui`
  + same problems as `notebook`
- `autonotebook` #443
- `contrib` a place for PRs such as #158, #94?
- `utils`  expose this due to some nice features?

additionally, for a transition period:

- `_tqdm_notebook`
- `_tqdm_gui`

**Comment by chengs** [comment]
@casperdcl 
perhaps ``tqdm.auto`` is better than ``tqdm.autonotebook``

**Comment by casperdcl** [comment]
k's, will change it

**Comment by chengs** [comment]
Move the content of #610 here. 

Since some critical errors are reported, which are all related to TMonitor, global thread, or global tqdm.__instances set.

Perhaps, it is better to provide a simple version (maybe ``tqdm.simple.tqdm`` and ``tqdm.simple.trange``), without the intergration of the functions above.  It will look like just a wrapper of an iterator.
```
class tqdmSimple():
    def __init___():
        self.iters = iters
        #only this, nothing else
        #no Tmonitor
        #no cls.__instances.

    def __iter__(self):
        for obj in self.iters:
            yield ....
            [print progress]
```

Indeed, it will not have some good features such as auto refresh, but it won't cause complicated errors). And then, tqdm with all features can be constructed on the basis of the simple version. 

For instance, the ``simple_progress`` in the test cases.

**Comment by chengs** [comment]
@casperdcl maybe also consider #604 (nosetest to pytest for test cases)? And use py3 to run performance tests (as py2.7 is going to be outdated)?

**Pull request closed without merging**
