### PR TITLE
Add fixed width bar `bar_width` and chop overflow on ncols

### LINKED ISSUE #623: specify bar width format-spec
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

I can't find it, maybe I'm stupid, but I'd like to be able to set a width for the right side data (something like this)
```

Messages            : 100%|█| 99/99 [00:02<00:00, 36.14it/s]
Message             : 100%|█| 3/3 [00:00<00:00, 544.17it/s]
Channels            :  95%|█▏           | 36/38 [08:54<00:22, 11.18s/it]
Relations           : 100%|█| 99/99 [00:00<00:00, 157.06it/s]
```
It would be nice, to make it possible to align the end of the bar (channels is the awkward one here)

### LINKED ISSUE #690: set_description causes ghosting with long text
I'm using set_description() with a filename, so I can easily show which file is currently being processed.

If a long filename comes along, I think it's becoming multiline, and then when the next file (that isn't long) comes up, it leaves a ghost trail on the screen, very similar to when you use print() instead of tqdm.write().

I have simply truncated my filenames to a fixed size, but in an ideal world it would be nice to have the option of truncating this automatically as you will know exactly how many characters there are left available on screen once everything else is rendered. I'm simply guessing.

Or, is this a rendering issue that can be fixed and leave the multiline implementation as is?

### PR DESCRIPTION
**Pull request by jeking3**
- added bar_width to initializer and format_meter
- added better ncols handling for overflows on l_bar, bar, r_bar
- added tests

This fixes #623
This fixes #690
This helps prevent the spillover seen in #630

This option (bar_width) prevents the bar portion of the output from being resized dynamically, and makes the r_bar portion dynamic (it gets chopped).  This addresses some of the concerns of #630 as well, but does not make an individual bar multi-line capable.  It just ensures you do not get multiple lines.

If the l_bar side is larger than ncols, you get ncols of l_bar.
If l_bar + bar is larger than ncols, you get l_bar + some of the bar.
If t_bar + bar + r_bar is larger than ncols, some of r_bar gets chopped.

Is there anything else I need to do for this to be accepted?

Thanks.

- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
- [x] If applicable, I have mentioned the relevant/related issue(s)

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

### CODE REVIEW

**Comment by jeking3** [comment]
@casperdcl anything else I need to do with this to get it moving?

**Comment by casperdcl** [comment]
Thanks @jeking3 for bumping this PR; I didn't look at it when implementing #800. It looks like both need to be combined. `__format__` is more pythonic and avoids adding even more clutter to the argument list (`bar_width`), but the `ansilen` logic is needed to fix #690

**Comment by jeking3** [comment]
Regarding the clutter: I was just following the pattern that was existed when I wrote this code.  It solves a serious issue that I could not get around by allowing the left, bar, and right sides of the progress bar to be set to a fixed width that cannot change.  I've never seen the progress bar jump or duplicate itself on multiple lines since I put this in place.  I've been using this for over 4 months, and it is (or at least, was...) properly tested, but since it was not actioned and the master code has moved forward, it looks like I'll need to spend more time on it, but I'd like to know it would be considered before I spend that time as it's difficult to schedule right now.

**Comment by casperdcl** [comment]
@jeking3 don't worry about spending time on this; I'll rebase your commits in a new PR and ping you. Can't promise when as I don't get paid for this :P

**Pull request closed without merging**
