### PR TITLE
leave=True by default, doc updates

### PR DESCRIPTION
**Pull request by casperdcl**
Addresses #115

### CODE REVIEW

**Comment by lrq3000** [comment]
Alright, fine with me. Plus, leave=True works alright with nested or
absolutely positioned bars so changing this parameter's default won't
diminish out-of-the-box tqdm's other features.

2016-01-25 9:34 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by casperdcl** [comment]
yes. I'd still rather wait for milestone 4.0.0 to merge this

**Comment by lrq3000** [comment]
Yes ok, good call, we'll merge this by v4

**Comment by lrq3000** [comment]
Fails because of different default behavior with `nested`, but since this feature will be removed in v4, we don't care.

**Comment by lrq3000** [comment]
Working on fixing the unit test right now.

**Comment by lrq3000** [comment]
I tried to reproduce the weird UnicodeEncodeError on my local Py26 install, and it simply doesn't happen. So I guess that Travis is silently dropping Py26 along Py32.

I still applied a workaround, because I think that an encoding error should not prevent `tqdm` from printing infos (after all, tqdm is not the end-user app, but only a widget for other apps, so it should not break the parent app, at least that's my point of view). However, I know that skipping exceptions is not really a good thing to do usually, so what do you think @casperdcl ? Should we keep this workaround, or drop Py26 right now (we will do it eventually anyway)?

**Comment by lrq3000** [comment]
Ok I've found the culprit, give me a sec, I'm finalizing it.

**Comment by lrq3000** [comment]
Ok fixed the issue. It was all because of the `test_all_defaults()` unit test, which is the only test that printed in the terminal directly (on `sys.stderr` as is the tqdm default) instead of in a StringIO() fake file.

This produced a weird issue that happened only in Py26 on Travis and with `leave=True` (these 3 conditions were necessary):

 * with the previous `leave=False` and because there's no sleep in the loop, the bar hadn't any time to print anything but the initial step `0/3` (no bar) and then it was cleaned up because `leave` was False.
 * with `leave=True`, this forces the bar to print at closing.
 * the test `test_all_defaults()` printed directly to sys.stderr instead of StringIO, in order to fully test the default config. So it printed into Travis virtual terminal.
 * Travis's terminal supports unicode it seems, so `tqdm` detected that it supported unicode and by default it tried to print a unicode bar at the end of the loop in the unit test.
 * All these steps work very well for all Python versions, except Py26, which seems like to choke on unicode strings in this virtual terminal.

Now, the question is: does Py26 support unicode strings at all, or not (and this only failed because there's an incompatibility somewhere between Py26 and Travis's virtual terminal)?

@casperdcl, could you please try to install Py26 locally and tell `tqdm` can print in unicode inside? I cannot test on Windows, because the terminal doesn't support unicode... (but I tested with colorama and it seems nested bars don't work, implying Py26 can't do unicode, but I'm not sure, it may be that colorama is incompatible with Py26 or something like that).

In case Py26 doesn't support unicode at all, this would mean we should adapt `tqdm` to this issue, to only print in `ascii` if it's not at least Py27. And also, `position`/`nested` wouldn't be supported at all in this Python version...

**Comment by lrq3000** [comment]
Todo:
- [ ] Confirm if Py26 supports unicode at all, and adapt `tqdm` if necessary.
- [ ] Choose if we keep workaround?
- [ ] Rebase and clean up commits (remove "Debug commits")
- [ ] Merge PR and rebase `position` PR.

**Comment by casperdcl** [comment]
I already merged this PR into #87 a while back, probably needs to be merged again. Don't think we should rebase #87 as it's quite a major branch...

**Comment by lrq3000** [comment]
@casperdcl Do as you see fit, you're more experienced with rebasing and merging than me :) I just said that because I thought that's what you would prefer, but I have no preference. Just don't forget to remove the 2 debug commits!

**Comment by lrq3000** [comment]
But I think #87 is almost done, right? With the great job you did there, I think that's enough for now to make a new release ;)
And sorry about not being very present lately, lots of stuff going on professionally (a new job!), but I'm trying to keep up on this project regularly now.
I forgot that I had to fix the timing test on #87, I'm going to fix that now!

**Comment by lrq3000** [comment]
In fact I think the simplest would be to just port the changes to #87, and just close this branch, the changes will be merged from #87.

**Comment by casperdcl** [comment]
Hey no worried @lrq3000 congrats on the new job, hope it goes well. Yeah sorry about my absences too but we're all volunteers on this hobby project so maybe no need to apologise ;)

**Comment by casperdcl** [comment]
merged into #87

**Comment by lrq3000** [comment]
Thank's @casperdcl, I like my new jobs a lot! :D Yes, and it's opensource anyway, so anyone can submit patchs in ;)

**Pull request closed without merging**
