### PR TITLE
OOP

### PR DESCRIPTION
**Pull request by casperdcl**
Classes and functions with closure over mutables... Also minor bugfixes. Addresses #22 #24 #25

### CODE REVIEW

**Comment by casperdcl** [comment]
Ready for merge

**Comment by hadim** [comment]
Nice work @casperdcl . I let you merge it.

**Comment by casperdcl** [comment]
Ack tried merging as per github's recommended command-line method and have
2 ugly merge messages. Should rebase next time :)

--

**Comment by hadim** [comment]
Yeah always rebase a PR (forgot to mention it sorry) :-)

**Pull request merged**
