### PR TITLE
Fix Travis use conda to build pandas instead of pip

### PR DESCRIPTION
**Pull request by lrq3000**
Trying to make Travis use conda to install pandas instead of building from source via pip. This should dramatically reduce load and time spent (4.2 min - 3.6 min to pip install pandas).

See also discussion at #217 and useful tutorial at [this link](http://sburns.org/2014/03/28/faster-travis-builds.html).

### CODE REVIEW

**Comment by lrq3000** [comment]
By using `pip install conda` (the old way to install conda, now it should be via miniconda), we get the [error described here](https://github.com/conda-forge/serpent-feedstock/issues/2), which is in fact due to an unupdated conda. So it seems that the conda available on pipy is out-of-date, I wonder why it's still there?

**Comment by lrq3000** [comment]
So I could make it work using `pip install conda` on Py2.7 by removing `conda update conda --yes`. But it didn't work on Py3.5, dunno why, so we probably ought to use miniconda now to make it work on Travis.

However, I tried something else: caching. While conda builds reduced the build time from 4.2 min to 1.5 min, caching reduces the build time to < 1 min. So I guess we'll keep caching.

Travis documentation explicitly says we shouldn't cache binaries, so that's why I'm not going to try to mix caching + conda, so we are using only pip for the moment.

If we ever get into some weird troubles, we should remember to clear the cache from Travis website interface.

**Comment by casperdcl** [comment]
so @lrq3000 this PR continues to use pip, just with caching? and is mergeable?

**Comment by lrq3000** [comment]
@casperdcl Yes for both: it still uses pip, so if we get into troubles we need to clear the cache (to force the refresh of the packages, for example if one of them gets updated, I'm not sure Travis is able to know when to automatically refresh the cache), and yes it's mergeable as far as my tests go, it seems everything pass OK.

**Comment by lrq3000** [comment]
About the cache refresh, what I mean is that the cached packages should always work, but in case they get updated on pip and we want to use a feature that is available only in the latest releases, we will probably need to refresh the cache manually.

**Comment by CrazyPython** [comment]
@lrq3000 Ever thought about joining us at tqdm/tqdm.cpp? Right now we have three developers...

**Pull request merged**
