### PR TITLE
IPython aliased imports fix

### PR DESCRIPTION
**Pull request by casperdcl**
attempt to fix aliased imports as per #187

### CODE REVIEW

**Comment by casperdcl** [comment]
@QuLogic does this fix your issue?

**Comment by QuLogic** [comment]
Yep, seems to work fine. Would be nice if the `FutureWarning` was caught too.

**Comment by casperdcl** [comment]
can you post the `FutureWarning` output? don't know if that's the sort of thing we should be suppressing.

**Comment by lrq3000** [comment]
On IPython 4 there is no futurewarning. What version of IPython are you running @QuLogic please?

**Comment by QuLogic** [comment]
Yes, that's right it's IPython 3 with the warning `:0: FutureWarning: IPython widgets are experimental and may change in the future.` I understand the reasoning behind the warning, but I'm not directly using a widget and it seems like the tqdm team is on top of the backwards/forwards-compatibility issues so that the warning is kind of superfluous.

**Comment by lrq3000** [comment]
Ah yes so in this case I'm not sure we can or should do anything about it. First because I'm not sure how IPython issues the warnings (normally they should be suppressed by default for the end users, except if you change filters. But if they don't use the `warnings` core lib, then it may not be possible to catch this), and secondly because it's considered non pythonic for a lib to catch warnings, they should be managed by the end user.

Anyway this does not hamper the functioning of tqdm, and the latest versions of IPython suppressed these warnings. Ah, the joy of managing cascaded deprecation warnings... See also the discussion at #192.

**Pull request merged**
