### PR TITLE
License

### PR DESCRIPTION
**Pull request by casperdcl**
addresses #121

### CODE REVIEW

**Comment by lrq3000** [comment]
Great move @casperdcl !
Just one feedback: instead of saying "A CC-BY-SA alternative is also available.", maybe you can just say "or CC-BY-SA v4 at your convenience". This is used in GPL and other libraries to specify when the library allows to use new versions of the licence according to the user's choice.

**Comment by casperdcl** [comment]
Sure @lrq3000 I think we also need a COPYING(.license) file containing the LGPL and GPL text (according to the lgpl page on gnu.org).

**Comment by EdwardBetts** [comment]
It still seems confusing that tqdm is going to be LGPL, but the LICENSE file says that new contributions are released using the MIT license. It isn't possible to take something that is LGPL and release modifications to it with an MIT license.

Wouldn't it make more sense to make it clear that tqdm is LGPL and any future changes to it are also LGPL?

**Comment by casperdcl** [comment]
That's both true and false depending on your definition of modification... If you write a method which augments tqdm's abilities you have full control over what licence to release that extra bit of code under (if it's open source on github we assume MIT unless otherwise specified). That's the whole point of the LGPL! If you make a minor modification to a single lgpl line of code, then yes it's still lgpl (or gpl).

**Comment by EdwardBetts** [comment]
Currently it is complicated for a contributor to determine what license they should use for their contributions. They need to look through the commit history to work out if they should release the change as MIT or LGPL. It would be simpler if the library were under a single license.

**Comment by lrq3000** [comment]
Edward, as a contributor you don't have to choose, the LICENCE implicitly
specify that contributors choose MIT for their contributions unless another
licence is explicitly specified by the contributor. So that contributors
can just contribute without specifying anything, the MIT will be choosen
for their contributions by default.

The licencing ambiguity was mainly for users (i.e., third-party
developpers) of the library, not for contributors, because users didn't
know if using this library would force their own whole software into
CC-BY-SA. Now it's clearer: users can just assume the library to be LGPL
and they're safe (which is the most restrictive licence between the two
selected for this project).

2016-02-10 9:50 GMT+01:00 Edward Betts <notifications@github.com>:

**Comment by lrq3000** [comment]
Ah but I see your point Edward: let's say someone changes one of Casper's
contributions. By the licence, the contributions will be implicitly be put
under MIT, but in reality it's still LGPL since it's a modification of
Casper's code.

I think in this case, you can assume that the changes per se are MIT, but
the original base code is LGPL. But that becomes quite confusing indeed and
I'm not even sure it would hold legally, so yeah we should maybe do
something about it.

But anyway, using LGPL instead of CC-BY-SA is already a lot better. We need
to think if we should go further. Maybe we should ask the Free Software
Foundation for advices?

2016-02-10 10:44 GMT+01:00 Stephen LARROQUE <lrq3000@gmail.com>:

**Comment by EdwardBetts** [comment]
@lrq3000 I don't think we need advice from the FSF, they would just recommend being clear that the library is LGPL 3+ (they would probably recommend GPL 3+) and all future contributions are released under the same license. Then there is no confusion.

**Comment by lrq3000** [comment]
Putting the whole library under LGPL would indeed be clearer but also more
restrictive, since it would licence code under LGPL that were MIT before
(or would be in the future).

2016-02-10 11:17 GMT+01:00 Edward Betts <notifications@github.com>:

**Comment by EdwardBetts** [comment]
@lrq3000 The pre-LGPL version will still be available on github and pypi. If somebody wants a MIT version of this library they can either download the most recent version before @casperdcl started contributing, or they can figure which contributions were supplied by @casperdcl and rewrite them.

**Comment by casperdcl** [comment]
@lrq3000 as I was trying to explain, if a contributor modifies lgpl-code, their contrib is lgpl (unless they specify gpl) they could also insist on any other license but in that case it will be at our discretion whether to merge that PR. If they modify MIT-code or add something completely new it'll be MIT licensed, unless they specify otherwise (again, our discretion).

1. We cannot convert all the MIT code to another license because that would involve contacting too many contributors, many of whom we know probably won't respond.
2. We shouldn't say assume all further contribs are (L)GPL because that causes the same problem as before - if say we want to in future dedicate this all to the public domain, we'll have to contact too many people. If we say only a few devs who have written most of the code retain the 'least' permissive licences then it makes moving forward much easier.

**Comment by lrq3000** [comment]
Ok to Edward and Casper, you're correct.

About your points 1 and 2 Casper, I disagree: we can (indirectly) relicence
the whole library under LGPL since MIT explicitly allows to sublicence (so
we can sublicence the whole project under LGPL and keep the MIT licence as
required). Also, copyright owners of a project can relicence without the
permission of all the contributors (but then in our case, who are the
copyright owners? Does this include Noamraph who isn't reachable anymore?).

But about what we should do, I'm still not sure.

2016-02-10 19:11 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by kmike** [comment]
That's a bummer. Even though LGPL can be OK for 99% cases, there are dark sides - it is written with C in mind, and e.g. it can be disputed what does static linking means for Python, or how to interpret `install_requires` which include LGPL software, or what to do if you get LGPL-based package as a transitive dependency - do you still have to add a notice somewhere? If I use tqdm in a MIT-licensed package do I have to modify this MIT-licensed project now, e.g. to

* add instructions on how to get tqdm copy and its source code;
* host tqdm source code myself for 3 years to make sure source code can be provided if I use tqdm in an executable (do docker images count as executables? do python scripts count as executables?);
* add LGPL copyright for tqdm to my package (and require users of my package to do the same?);
* make sure users can install and use updated tqdm versions (so no version limiting in install_requires, e.g. I can't pin tqdm version to be less than 5.0?)

(based on https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-%28lgpl-3%29). 

I'm a developer, not a lawyer; I don't want to deal with all that, and I don't want people who use my software to deal with all that. So MIT -> LGPL relicensing is a regression for me, probably a show-stopper in some cases. I'll probably still use tqdm in internal projects and scripts, but not as a dependency in a public open-source project. That's sad we have to do this change, and I don't like at all how we got here. This should have been discussed before applying code changes which now require re-licensing of the whole project. I don't have any concrete suggestions on how to avoid the re-licensing though.

**Comment by lrq3000** [comment]
Please bear in mind that it is not a relicencing of the MIT parts into
LGPL, but of the CC-BY-SA parts into LGPL. I still think that LGPL is
better than CC-BY-SA, but of course that's not a perfect solution, only a
better solution compared to the current state.

2016-02-16 15:43 GMT+01:00 Mikhail Korobov <notifications@github.com>:

**Comment by kmike** [comment]
Yeah, I agree that LGPL is better than CC-BY-SA.

**Comment by kmike** [comment]
I don't get the difference between relicensing CC-BY-SA parts to LGPL and relicensing the whole project to LGPL though; won't the former imply the latter?

**Comment by lrq3000** [comment]
Technically, no, but in practice yes because Casper contributed a lot to
the code. So a user of the library may consider the whole project as under
CC-BY-SA currently, but for a dev who want to fork the project, there are a
lot of commits that can be reused under MIT.

2016-02-16 16:25 GMT+01:00 Mikhail Korobov <notifications@github.com>:

**Comment by lrq3000** [comment]
So if we change only Casper's commits licence and not others, the MIT
commits may still be forked under MIT (provided that they are not direct
modifications of Casper's code). At least that's my interpretation, but
IANAL.

2016-02-16 19:33 GMT+01:00 Stephen LARROQUE <lrq3000@gmail.com>:

**Comment by casperdcl** [comment]
I agree things like the hosting source for three years is silly. I was hesitant to bring this up initially since it sounds odd but... Mozilla Public Licence? It was designed specifically for scenarios like the one we find ourselves in, I think.

**Comment by lrq3000** [comment]
No it doesn't sound odd at all Casper, that's a good suggestion :)

I don't know much about the MPL but indeed there are several examples of
successful hybrid softwares mixing closed source and open source libraries,
so this is a possibility. Anyone with more knowledge about this licence?

2016-02-16 19:51 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by casperdcl** [comment]
MPL also allows sublicencing and specifically mentions GPL as an option, so this seems safest. I think it also addresses @kmike's points

**Pull request merged**
