### PR TITLE
contrib.telegram

### LINKED ISSUE #948: 'reverse' hook to retrieve current progress/postfix
I'm looking for a way to broadcast tqdm display to a telegram bot. I know there's https://github.com/ermakovpetr/tg_tqdm but I'm not satistfied with it since it breaks the standard output and doesn't work in notebooks.
What are my options to achieve this?

### PR DESCRIPTION
**Pull request by casperdcl**
Example use pushing to Telegram.

- [x] document
- [x] subclass work-around #509
- [x] use `requests`
  + [x] make non-blocking
- fixes #948

To test:

```bash
$ pip install 'git+https://github.com/tqdm/tqdm.git@telegram#egg=tqdm'
```
```python
from time import sleep
from tqdm.contrib.telegram import tqdm, trange
for i in trange(10, token='1234567890:THIS1SSOMETOKEN0BTAINeDfrOmTELEGrAM',
                chat_id='0246813579'):
    sleep(1)
```

Idea from [tg_tqdm](https://github.com/datagym-ru/tg_tqdm):

### CODE REVIEW

**Comment by JulienMaille** [comment]
I see you've taken inspiration from original tg_tqdm which relies on telepot (a discontinued library). Everything can be done with simple post requests like shown in this fork https://github.com/dpodvyaznikov/tg_tqdm/blob/9d34f3bb779fe4209cc36ce05b0d19662ad69820/tg_tqdm/_tg_tqdm.py
Would it make sense to pass a 'Bot' object (with a write method) to the constructor in order to make it more versatile?

**Comment by casperdcl** [comment]
`write` wouldn't get called in a notebook though.

**Comment by JulienMaille** [comment]
I'll show you what I have in mind. But before, it seems it breaks nested progressbar, am I correct?

**Comment by JulienMaille** [comment]
Something like this
```python
from tqdm.auto import tqdm as tqdm_auto
from tqdm.utils import _range

class tqdm_telegram(tqdm_auto):
    def __init__(self, *args, callback=None, **kwargs):
        """
        Parameters
        ----------
        token  : str, required. Telegram token.
        chat_id  : str, required. Telegram chat ID.
        callback  :  method that will receive the progressbar content on display
        See `tqdm.auto.tqdm.__init__` for other parameters.
        """
        self.callback = callback
        super().__init__(*args, **kwargs)

    def display(self, msg=None, **kwargs):
        super().display(msg=msg, **kwargs)
        fmt = self.format_dict
        if 'bar_format' in fmt and fmt['bar_format']:
            fmt['bar_format'] = fmt['bar_format'].replace('<bar/>', '{bar}')
        if self.callback is not None:
            self.callback(self.format_meter(**fmt))


def ttgrange(*args, **kwargs):
    """
    A shortcut for `tqdm.contrib.telegram.tqdm(xrange(*args), **kwargs)`.
    On Python3+, `range` is used instead of `xrange`.
    """
    return tqdm_telegram(_range(*args), **kwargs)


# Aliases
tqdm = tqdm_telegram
trange = ttgrange
```
Which would be called like that:

```python
tg_bot = TelegramIO(TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID)
iterator = ttgrange(nb_epochs, desc='training', unit='epoch', callback=tg_bot.write)
```

**Comment by casperdcl** [comment]
@JulienMaille should be good to try now (much quicker too than any of the other implementations)

**Comment by JulienMaille** [comment]
Looks good!

**Comment by JulienMaille** [comment]
> I'll show you what I have in mind. But before, it seems it breaks nested progressbar, am I correct?

@casperdcl unless there's something wrong on my side, it seems that nested progressbar was broken in the past weeks.

**Comment by casperdcl** [comment]
Specifically for `tqdm.contrib.telegram.tqdm` or also for `tqdm.tqdm`?

**Comment by JulienMaille** [comment]
I'm sorry for the lack of details, I was thinking that maybe you would have recent change in mind and my remark would ring a bell. Right now I've tested only with `ttgrange`

**Comment by casperdcl** [comment]
I used `ttgrange = tqdm.contrib.telegram.trange` all the time in notebooks and nesting works fine. No, I can't think of any recent change which could've caused an issue.

**Comment by casperdcl** [comment]
ah broken when using nested contrib.telegram/discord on the the CLI in `tqdm==4.49.0`... just opened #1074

**Pull request closed without merging**
