### PR TITLE
Add `total` support to `tqdm.pandas()`

### LINKED ISSUE #364: tqdm_notebook and tqdm.pandas fails when given *total* argument.
My code:

>import tqdm
df = pandas dataframe with 1000 rows
tqdm.tqdm_notebook().pandas(total="1000")
df.progress_apply(myfunction, axis=1)

The error:

>C:\pythonstuff\lib\site-packages\tqdm\_tqdm.py in inner(df, func, *args, **kwargs)
    511                     deprecated_t[0] = None
    512                 else:
--> 513                     t = tclass(*targs, total=total, **tkwargs)
    514 
    515                 # Define bar updating wrapper
TypeError: type object got multiple values for keyword argument 'total'

Without specifying *total* it seems to work, but I don't get a percentage from the output. Also there is an extra bar.

tqdm_notebook_pandas

### PR DESCRIPTION
**Pull request by chengs**
@casperdcl 
I think here it should be a warning, because normally total should be automatically computed by tqdm. and only a few cases need manually set total. Like this:
screen shot 2018-04-12 at 12 16 11 pm

### CODE REVIEW

**Comment by chengs** [comment]
@casperdcl don't know why travis-ci has an error on python2.7, on my computer it works...

**Comment by casperdcl** [comment]
@chengs I don't think the warning is a good idea - if people specify their own `total` they probably know what they're doing. Please check out the [`sub_total`](https://github.com/tqdm/tqdm/tree/sub_total) branch.

**Comment by casperdcl** [comment]
thanks for the unit tests - I left them in.

**Comment by chengs** [comment]
@casperdcl, about warning, OK. you make the final decision, so no warning then.

**Comment by casperdcl** [comment]
Redundant lines? Which ones? Are they still in `devel`?

**Comment by chengs** [comment]
@casperdcl no, the devel is good. Ok to go.

**Pull request merged**
