### PR TITLE
env var override support

### LINKED ISSUE #370: Make dynamic_ncols=True the default
Any reason why `dynamic_ncols` is not True by default?

- [X] I have visited the [source website], and in particular
  read the [known issues]
- [X] I have searched through the [issue tracker] for duplicates

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#help
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

### LINKED ISSUE #612: Allow to turn off tqdm via environment variables
often I use the same code on my local dev machine and a cluster node. To not mess up the log files I normally turn off tqdm. While this is a simple change in the python code, I think it would actually be more convenient to let tqdm check for environment variables and thereby add some level of system level control over tqdm.

e.g. `TQDM=disabled python run.py` could quickly disable tqdm in any script. 
This should be easy to implement using `os.environ.get()`. I can compile a PR if you like this proposal

- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates

### LINKED ISSUE #614: support global config to override defaults
1. look for e.g. "$HOME/.tqdm.config" to override defaults
2. alternatively/additionally use os.environ.get("TQDM_CONFIG", '')

helps with e.g. #370, #612, #619, #950, #1061, #1318

The second (os.environ) option would be great to fix https://github.com/tqdm/tqdm/issues/370#issuecomment-421809342 (have `tmux` alter `TQDM_CONFIG` to have `dynamic_ncols`)

### LINKED ISSUE #619: Turn off tqdm from application code
- [X] I have visited the [source website], and in particular
  read the [known issues]
- [X] I have searched through the [issue tracker] for duplicates
- [X] I have mentioned version numbers, operating system and
  environment, where applicable:

```
4.26.0 3.6.6 (default, Aug 21 2018, 23:42:39) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] darwin
```

I'm using a package that uses `tqdm` internally and I'd like to disable tqdm *from within application code*.

https://github.com/tqdm/tqdm/issues/612 would've been ideal. It was closed because the solution solved the problem for the author of the issue but not for us since we cannot modify library code. Thanks.

### LINKED ISSUE #1318: add configuration to turn off progress bars
- [ ] I have marked all applicable categories:
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [x] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

```
4.64.0 3.8.13 (default, Apr  1 2022, 11:52:33)
[Clang 12.0.0 (clang-1200.0.32.29)] darwin
```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=
[StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

Hi,

`tqdm` is very useful during development to understand the progress of your code. However, if this code is deployed somewhere that doesn't have a regular tty, e.g. CI systems or servers, the progress bar could interfere with the regular logging of the application, e.g. for ingestion into systems like AWS CloudWatch, SumoLogic, Spluk or others.

I think it would be nice if `tqdm` could be configured to be a no-op. For example using an environment variable:

```bash
python my-script.py # tqdm progress bar emitted as usual

env TQDM_DISABLE=true python my-script.py # tqdm does nothing
```

### PR DESCRIPTION
**Pull request by casperdcl**
- environment variables to override defaults (`TQDM_*`)
  + e.g. in CI jobs, `export TQDM_MININTERVAL=5` to avoid log spam
  + add tests
  + add docs (`tqdm.utils.envwrap` & e.g. `export TQDM_MININTERVAL=5`)
- fix & update CLI completion
- fix & update API docs
- minor code tidy: replace `os.path` => `pathlib.Path`
- fix documentation image hosting

---

- fixes #370, fixes #612, fixes #614, fixes #619, fixes #1318
- closes #950, closes #921, closes #1061

### CODE REVIEW

**Comment by biswaroop1547** [comment]
awesome 🚀

**Comment by sisrfeng** [comment]
For those who are curious about the implementation: (It seems to be a general and convinient method to "Override parameter defaults via `os.environ[prefix + param_name] " )

https://github.com/tqdm/tqdm/pull/1491/files#diff-a80e72b5f3679063ef2e742eba24c88112f0e189d34acc70cf2dc866e9af84b8R35


```python
def envwrap(prefix, case_sensitive=False, literal_eval=False, is_method=False):
    """
    Override parameter defaults via `os.environ[prefix + param_name]`.
    Precedence (highest first):
    - call (`foo(a=3)`)
    - environ (`FOO_A=2`)
    - signature (`def foo(a=1)`)
    Parameters
    ----------
    prefix  : str
        Env var prefix, e.g. "FOO_"
    case_sensitive  : bool, optional
        If (default: False), treat env var "FOO_Some_ARG" as "FOO_some_arg".
    literal_eval  : bool, optional
        Whether to `ast.literal_eval` the detected env var overrides.
        Otherwise if (default: False), infer types from function signature.
    is_method  : bool, optional
        Whether to use `functools.partialmethod`. If (default: False) use `functools.partial`.
    Examples
    --------
    ```
    $ cat foo.py
    from tqdm.utils import envwrap
    @envwrap("FOO_")
    def test(a=1, b=2, c=3):
        print(f"received: a={a}, b={b}, c={c}")
    $ FOO_A=42 FOO_C=1337 python -c 'import foo; foo.test(c=99)'
    received: a=42, b=2, c=99
    ```
    """
    i = len(prefix)
    env_overrides = {k[i:] if case_sensitive else k[i:].lower(): v
                     for k, v in os.environ.items() if k.startswith(prefix)}
    part = partialmethod if is_method else partial

    def wrap(func):
        params = signature(func).parameters
        overrides = {k: v for k, v in env_overrides.items() if k in params}
        if literal_eval:
            return part(func, **{k: safe_eval(v) for k, v in overrides.items()})
        # use `func` signature to infer env override `type` (fallback to `str`)
        for k in overrides:
            param = params[k]
            if param.annotation is not param.empty:
                typ = param.annotation
                # TODO: parse type in {Union, Any, Optional, ...}
            else:
                typ = str if param.default is None else type(param.default)
            overrides[k] = typ(overrides[k])
        return part(func, **overrides)
    return wrap
```

**Comment by casperdcl** [comment]
Well... [tqdm.utils.envwrap](https://tqdm.github.io/docs/tqdm.utils/#envwrap) API was updated in #1493 to fix cross-platform compatibility

**Pull request merged**
