### PR TITLE
Exponentially weighted moving average, tests, documentation

### LINKED ISSUE #48: Be able to display the instantaneous speed of the loop
Currently, tqdm shows the average speed of the loop, given the time it took since it started and the amount of iterations done. In some common cases this is not helpful, and the instantaneous speed would be better (the instantaneous speed being the inverse of the amount of time since the last iteration).

The classic case where this would be useful is for stoppable scripts that skip what was already done when you run them a second time after stopping them.  For example, a script that converts a million images and checks before that the converted image already exists. If you already converted 20% of the images, the second run of the script will execute 20% of the iterations at 300 its/s, while the standard speed should be 1 it/s. When the script reaches the first unconverted image, it still says that the speed is around 300 its/s, and you’ll have to wait several thousands of iterations (so several hours) before the speed comes back to something more reasonable (but the estimated remaining time will still not be correct).

For such scripts, it could therefore be useful to display the instantaneous speed, or we could even create an algorithm that uses the minimum, maximum, and median speed per iteration to give a realistic estimation of speed and remaining time that would work for any use case, instead of using only the average **or** the instantaneous speed depending on a boolean setting. The new estimations will be much more dynamic, but not ridiculously changing like Windows progress bars that only use the instantaneous speed and can switch from a few seconds to several hours in a heartbeat.

More statistics than minimum, maximum, and median speed (like quartiles) would increase the precision of the estimation, but these three values are enough for now in my opinion.

### PR DESCRIPTION
**Pull request by casperdcl**
fixes #48

### CODE REVIEW

**Comment by casperdcl** [comment]
Everyone ok with this?

**Comment by lrq3000** [comment]
Please wait, I'll try your changes tomorrow morning and I'll merge it myself if everything's ok :)

**Comment by casperdcl** [comment]
Cool. You could try and come up with a way of actually testing the output properly... maybe manual calls to time.sleep, and then parse tqdm's output to extract its estimate of rate and check if it is above/below a threshold ...

**Comment by lrq3000** [comment]
I update your code @casperdcl to restore the old average rate when smoothing = 0 or None.

Also, I changed the remaining time calculation to use the provided rate. I'm not sure about this one, but I feel that if we change the rate, we should as well change the remaining time accordingly since the two are linked. But this can lead to an "optimistic" prediction of remaining time, while the old calculation (based on total average time) was "pessimistic"...

**Comment by lrq3000** [comment]
Thank's for the fixes. I'm still working on it, there are a few issues in some edge cases. I'm trying to fix them and make a unit test.

About the default value for smoothing, I have done a few tries, and 0.05 is a very good value (usually it's advised to use 0.03): this gives more weight to the average, but it also adapts quite fast to new changes, in a few decades of iterations.

**Comment by casperdcl** [comment]
I assumed you had changed it wile debugging and unit testing as it wasn't changed in the documentation. Will change it back...

**Comment by lrq3000** [comment]
Ah ok @casperdcl I understand. In fact I wasn't finished with the changes that's why I didn't change the documentation yet :)

I think I have found a reliable way to test for smoothing: I basically generate 3 runs: 1 with no smoothing, one with max and one with medium smoothing, and I just check that the rate is in the correct order (no smoothing < medium smoothing < max smoothing). Thus this doesn't slow down too much the whole unit test (but it's necessary to use time.sleep, else there's no delta_t to compute the smoothed rate...).

**Comment by lrq3000** [comment]
Alright! Everything's seems fine and Travis does not seem to significantly take more time now that I have included the smooth rate unit test. Merging this now :)

**Comment by casperdcl** [comment]
@lrq3000 you'll have to force-pull master as I rebased this...

**Comment by lrq3000** [comment]
@casperdcl I just needed to do a simple pull, no need to --force, I guess it automatically detected the rebase.

**Comment by casperdcl** [comment]
Nope, you need to force pull overwriting your local changes otherwise there'll be a few extra ugly commit messages (but no actual difference to the code, which is why it silently merges without complaining if you don't overwrite)

**Comment by lrq3000** [comment]
@casperdcl Ah maybe I did a `git pull --rebase`, because I already pulled before seeing your message. But anyway, I always check to see if there are those ugly merge messages, but found none :)

**Pull request merged**
