### PR TITLE
`asyncio.gather` API consistency with stdlib

### PR DESCRIPTION
**Pull request by MapleCCC**
Intended as a drop-in replacement of the stdlib `asyncio.gather()`, it would be much reasonable if the function interface is consistent with that of `asyncio.gather()` as well.

It also ensures that our interface doesn't violate the least-surprising principle. It would have been surprising and frustrating for a user to wanting to use `tqdm_asyncio.gather()` as a drop-in replacement to the stdlib `asyncio.gather()` but ending up being bitten by the trivial inconsistency.

### CODE REVIEW

**Comment by casperdcl** [comment]
doesn't look like tests are passing...

**Comment by MapleCCC** [comment]
Yeah, I forgot to update the unit test as well. It should be fixed now.

**Comment by casperdcl** [comment]
Thanks! Probably will break some workflows next release but does look necessary...

```diff
-await gather(list(map(double, range(30))))
+await gather(*map(double, range(30)))
```

**Comment by MapleCCC** [comment]
Considering that this PR introduces a backward incompatible change, shouldn't we make it into a future major release, as dictated by the [semantic versioning spec](https://semver.org/#summary) tqdm [follows](https://github.com/tqdm/tqdm/blob/master/CONTRIBUTING.md#semantic-versioning)?

**Comment by casperdcl** [comment]
I thought about it... technically breaking semver a bit but since 1. it's a submod and 2. fairly recently introduced so probably not that many users, I felt like sneaking it in a minor version bump may be better.

That being said, v5 really is overdue.

**Pull request merged**
