### PR TITLE
Avoid flake8ing .tox etc

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
@casperdcl looks like you may need to fix codacy setup.

**Comment by casperdcl** [comment]
@altendky I'm not sure this command would ever be executed in a directory which had e.g. a `.tox/` folder - it should only be ever executed by `tox` itself within a venv it created...

**Comment by casperdcl** [comment]
ah in any case I essentially this it in d9da3144767b9b164dd0eb812bef07a577383d0f

**Comment by casperdcl** [comment]
Thanks for your contributions, btw - you're now in https://github.com/tqdm/tqdm#authors :)

**Comment by altendky** [comment]
Perhaps it was the manual venvs I had created that caused it trouble.  I definitely ran tox and it choked on flake8 for a long time.  And excluding a couple things you expect won't solve such things in general.

**Pull request closed without merging**
