### PR TITLE
basic performance test, flake8 coverage for tests

### PR DESCRIPTION
**Pull request by casperdcl**
addresses #51

### CODE REVIEW

**Comment by casperdcl** [comment]
interestingly fails on my machine with `make` (runs reeeally slow) but runs fine with `make testnose`.

**Comment by lrq3000** [comment]
lol I was doing the change myself :p pulling your changes and adding some

**Comment by casperdcl** [comment]
Ah I see. It will fail if coverage is running, but pass with plain `nosetests tqdm -v`

**Comment by lrq3000** [comment]
Ah ok, yes that was weird. Ok so we need to put coverage off for this test. This is getting more complicated.

**Comment by casperdcl** [comment]
Pragma no cover doesn't help :(

**Comment by lrq3000** [comment]
Normal because the test is calling tqdm, which is covered! So we cannot avoid the overhead of coverage. We need to somehow specify in tox and travis that this test needs to be run without coverage. I'll see what I can do with some conditionals magic

**Comment by casperdcl** [comment]
Not really - it means coverage is always on, but the pragma makes stats ignored. Coverage should work in a way that it turns off for the entirety of `# pragma: no cover` blocks...

**Comment by lrq3000** [comment]
Ah ok, I didn't know, then it's not working as expected, but anyway I've heard the unit testers often have buggy pragma handling...

**Comment by lrq3000** [comment]
Ok I've just noticed the same behavior as you: with coverage, the performance is significantly slowed down. We need to find a way to prevent this :/

**Comment by lrq3000** [comment]
I could not find a way to fix this issue... I guess that maybe the culprit lies in the management of coverage by nose, maybe this makes nose run a lot slower to do the interface.

Anyway, this doesn't really change anything for us: as long as we define a relatively close performance threshold, we can use it in the future to check for performance regression: the overhead of the unit testing library being the same (presumably), that's ok.

Of course, if we could find a way to avoid this slowdown, this would be great :D I propose we leave this PR open for a few days and see what we can find to fix this issue. If in a few days nothing has been found, we merge and we'll see someday if we find something along the way.

**Comment by lrq3000** [comment]
We need to find a way to exclude the performance test from PyPy, because currently it takes too much time on Travis (we've gone from ~4 mins to ~12 mins!).

**Comment by lrq3000** [comment]
I think I have found a good compromise: I have excluded the performance tests from the usual tests, and I have created a tox env specifically to run only the performance tests, without coverage. This way, I could lower down the threshold like before, and it also saves on Travis resources since the performance tests are ran only once.

The only downside is that the performance tests are ran on Python 3 (the default env we have set in tox), not Python 2, but I think that's enough for now to avoid speed regressions.

If this seems ok to you @casperdcl, I think we can merge in the current state :)

**Comment by lrq3000** [comment]
Note for the future: we could also use the attrib plugin to tag slow tests and exclude them easily. The advantage is that this works wherever the tests are placed at (ie, no need to create a separate file, which was the initial reason why I wanted to place the performance tests inside tests_perf.py).

Sample test:
```
def test_big_download():
    import urllib
    # commence slowness...

test_big_download.slow = 1
```

Then just run:
```$ nosetests -a '!slow'```

See: http://stackoverflow.com/a/12671360/1121352

**Comment by casperdcl** [comment]
Thx @lrq3000 ... will re-look at this PR in a couple of days (don't think it's uber urgent, doesn't add to the actual tqdm code).

**Comment by lrq3000** [comment]
Nope, that's not urgent at all :) You can take your time

**Comment by lrq3000** [comment]
Also, maybe we could add nose-timer to time the duration of each test. But this adds one dependency that may become broken in the future. What do you think about it?

**Comment by casperdcl** [comment]
`nosetests` already prints total amount of time to run tests... and as discussed we can only somewhat measure overhead on different systems by comparing loops with and without `tqdm` (as currently implemented in one unit test)

**Comment by lrq3000** [comment]
That's not what I'm talking about, I'm clarifying: I didn't propose nose-timer to replace the performance tests, but as an addition BTW to measure future tests additions and make sure we don't add tests that spend too much time. Of course, this can also be tested locally, but it can be nice to have this info directly on Travis to see the evolution of each tests.

**Comment by casperdcl** [comment]
Don't really see the use... the tests already have more sloc than `_tqdm.py` ... don't want to get carried away. I think it's already pretty clear how long they take and nose-timer isn't worth the dependency. What do the others think?

**Comment by lrq3000** [comment]
Just a remark about nose-timer: it doesn't require to add any new line of code apart from adding the argument `--with-timer` to nosetests (and of course install the package in tox.ini):

`nosetests --with-coverage --cover-package=tqdm -d -v tqdm/ --with-timer`

This may still be useful for local tests :)

**Pull request merged**
