### PR TITLE
Fix `tqdm_notebook` fails with non-integer update (#456).

### PR DESCRIPTION
**Pull request by chengs**
Fix the issue #456. _Need further test on various ipython (jupyter) notebook versions._

- For tqdm, add round(n,5) on the progress var **n** to avoid overlong decimal progress values.
- For tqdm notebook,
    1. Change all **IntProgress** widgets to **FloatProgress** widgets.
    2. Add **float** and **round** on the progress var **n**, to avoid display problem.

Now it has output like the following
tqdm

### CODE REVIEW

**Comment by chengs** [comment]
It seems this modification cannot pass many tests. I will make a new version

**Comment by chengs** [comment]
Now all tests are passed. HOWEVER, it seems there is a problem on the color of the FloatProgress widget. Still working.

**Comment by chengs** [comment]
can someone have a look?

**Comment by chengs** [comment]
I will reconsider this, the current modification add too much overload.

**Comment by chengs** [comment]
@casperdcl now it seems OK

**Comment by casperdcl** [comment]
is this still an issue?

```python
from tqdm.auto import tqdm
with tqdm(total=int(1e5), leave=False) as t:
    while t.n < t.total:
        t.update(0.1)
```

seems to work fine for me now...

**Comment by casperdcl** [comment]
closing and #456 seems to be fixed now

**Pull request closed without merging**
