### PR TITLE
Support Google Colab

### LINKED ISSUE #618: [suggest] create a fallback option for ipywidgets in tqdm_notebook
It happens sometimes that a user forgot to install ``ipywidgets``. Or ``ipywidgets`` has a compatibility problem (eg, #187, #559, #558). In this case, I think we should have a backup plan with a reminder of installing ``ipywidgets``.

After experiments, I find that it is possible to use only IPython display function and HTML5 to make a simple but ugly progress bar (see blew). **It can works in google colab (can address #559, #558)**.

DEMO:
demo

As ``tqdm_notebook`` only uses ``ipywidget.IntProgress``. We can consider to write our own ``IntProgress`` class as a fallback solution. 

@casperdcl, If you think this is worth to do, I am glad to make a PR.

### PR DESCRIPTION
**Pull request by chengs**
This PR closes #618 #559 #588

**Objective**: Let ``tqdm`` support ``Google Colab`` (with minimum function). 

**Demo**: A Google Colab notebook is created for illustrating the function implemented. Anyone can copy and run it in his/her own Colab environment. See here (https://colab.research.google.com/drive/12QXaI5ZAiQJfK-19HVl8fyjyh79B-TMf) 

**Usage**: 

> Still under development, if you would like to use it now, please install the specific version based on ``v4.28.1`` by following the instruction blew

1. Install in ``Google Colab`` by typing  
```bash
!pip install --force https://github.com/chengs/tqdm/archive/colab.zip
```
2. Use ``tqdm`` as usual

**Screenshot**:
image

TODOs:
- [X] Instruction
- [X] Demo Colab Notebook
- [X] Add ``tqdmExperimentWarning``
- [X] Solve ``desc``
- [X] Better ``ncols``
- [X] Fix CSS
- [X] Format code
- [X] Let CI ignore the code in code coverage test
- [X] Ping @casperdcl

### CODE REVIEW

**Comment by chengs** [comment]
@casperdcl I think the current version is acceptable and is ready for merging. 

Please check this demo (https://colab.research.google.com/drive/12QXaI5ZAiQJfK-19HVl8fyjyh79B-TMf). 

PS. Perhaps we need add something in readme. I am not sure

**Comment by casperdcl** [comment]
Thanks @chengs ... will try to find time to look at this

**Comment by chengs** [comment]
ping

**Comment by Queuecumber** [comment]
Any chance of this being merged?

**Comment by casperdcl** [comment]
Sorry, I haven't had much time. Hopefully soon...

**Comment by Queuecumber** [comment]
Maybe it makes sense to add @chengs to the developer as per his request to lighten the load? He seems to have the motivation and you have 33 outstanding PRs many of which are from him

**Comment by chengs** [comment]
@Queuecumber Thanks for the support.

**Comment by chengs** [comment]
@casperdcl Colab has already built-in Ipywidgets support. The solution used in this PR is no longer needed. Let me close this PR.
image

**Comment by casperdcl** [comment]
oh interesting... @Queuecumber can you confirm this issue is fixed?

**Comment by Queuecumber** [comment]
Yeah looks like it is working, I had another output in the same cell that was writing HTML and I think they were conflicting which was making it look like tqdm wasnt working. When I move the tqdm loop to another cell it displays correctly.

**Comment by TezRomacH** [comment]
Is this alive? :)

**Comment by casperdcl** [comment]
@TezRomacH I think this issue has been fixed upstream. Going to close for now - will re-open if anyone confirms there's still an issue.

**Pull request closed without merging**
