### PR TITLE
Fix 'Set changed size during iteration' bug

### PR DESCRIPTION
**Pull request by vnetserg**
Tqdm version 4.19.8, Python 3, Linux. Faced the following bug:

```
# ... lines skipped
contrib/python/futures/concurrent/futures/_base.py:398: in result
    return self.__get_result()
contrib/python/futures/concurrent/futures/thread.py:55: in run
    result = self.fn(*self.args, **self.kwargs)
# ... lines skipped
contrib/python/tqdm/tqdm/_tqdm.py:712: in __init__
    self.pos = self._get_free_pos(self)
contrib/python/tqdm/tqdm/_tqdm.py:408: in _get_free_pos
    return max(inst.pos for inst in cls._instances
contrib/python/tqdm/tqdm/_tqdm.py:408: in <genexpr>
    return max(inst.pos for inst in cls._instances
contrib/tools/python/src/Lib/_weakrefset.py:60: in __iter__
    ???
E   RuntimeError: Set changed size during iteration
```  

Apparently, this problem has been reported before: #481 (Monitor thread was disabled).

It seems to be caused by the fact that `tqdm` does not take lock when it iterates over `_instances` in `_get_free_pos` method, which leads to a race condition if multiple `tqdm` instances are created concurrently. This problem seems to be still present in the upstream tqdm, so here is the fix that worked for me.

/cc @Kontakter

### CODE REVIEW

**Comment by vnetserg** [comment]
Any updates/thoughts on this?

**Comment by Kontakter** [comment]
@casperdcl – could you please look at this Pull Request?

**Comment by Kontakter** [comment]
@casperdcl – please, let merge this pull request

**Comment by casperdcl** [comment]
argh need more hours in a day :/

**Comment by casperdcl** [comment]
does #754 also fix this issue?

**Comment by Kontakter** [comment]
Yes, I think so. @orivej is our fellow

**Comment by casperdcl** [comment]
closed by #754

**Pull request closed without merging**
