### PR TITLE
Tqdm2

### PR DESCRIPTION
**Pull request by casperdcl**
local branch migrated from #34

### CODE REVIEW

**Comment by hadim** [comment]
@lrq3000 are you doing the modif and do you want me to take care of it ?

**Comment by casperdcl** [comment]
pandoc basically rules my life, I was going to use it to convert everything to rst and then manually tweak anything that was broken. Personally I prefer md, though... but since pypi doesn't support it we don't really have a choice.

**Comment by lrq3000** [comment]
You can do the stuff about __version__, I can do the rest :)

**Comment by hadim** [comment]
Well I am currently writing my PhD thesis with pandoc @casperdcl :-)

What do we do with version finally ?

**Comment by lrq3000** [comment]
@kmike is against reading from a file, so I guess we will use the AST.

**Comment by lrq3000** [comment]
Ehm... guys, could someone tell me how I can contribute to this branch? I cannot use my credentials...

**Comment by hadim** [comment]
`git co tqdm2` then you can comit and push to it

**Comment by lrq3000** [comment]
Yes I checked out but I cannot push directly on tqdm/tqdm, my usual credentials are refused.

**Comment by hadim** [comment]
that should work now (I modified your right in the org settings)

**Comment by lrq3000** [comment]
Ok all good, I had to use my private key password, which is a bit weird but ok.

**Comment by lrq3000** [comment]
Ah ok great, that's why it worked :) Thank's!

**Comment by lrq3000** [comment]
I'm working on converting the Markdown Readme to ReStructured Text

**Comment by lrq3000** [comment]
@casperdcl: no we don't need to include in the MANIFEST.in the *.py files that are inside the package specified in setup.py.

**Comment by casperdcl** [comment]
Ah ok. Gotta love `pandoc -o README.rst README.md`...

**Comment by hadim** [comment]
@lrq3000 can remove the blank line at the end of __init__.py please?

**Comment by lrq3000** [comment]
I finished the RST conversion, here's the result:
https://github.com/tqdm/tqdm/blob/tqdm2/README.rst

I have only one remaining issue with the grey blocks of the bar example, after `Here's what the output looks like:`. Spaces are not accepted, so I replaced by an underscore. If you find how to fix that, please tell me :/

**Comment by lrq3000** [comment]
@hadim: ok done

**Comment by lrq3000** [comment]
Here's an example build I did just now:

http://s000.tinyupload.com/index.php?file_id=26828683241520336490

Seems all good to me. Any suggestion or should we upload to pypi?

**Comment by hadim** [comment]
Seems fine to me. Wait for everyone approval.

**Comment by hadim** [comment]
And travis being happy also :-)

**Comment by lrq3000** [comment]
Ah I forgot, I need to remove Readme.md. Everyone's OK? The Readme.rst is good enough?

**Comment by hadim** [comment]
`README.md` is still here...

**Comment by casperdcl** [comment]
gimme a few min while I try to rebase the heck out of these ugly commits ;)

**Comment by lrq3000** [comment]
Ok I'm not doing any change until @casperdcl finish the rebase :)

**Comment by casperdcl** [comment]
Ok done with rebase. Nice work guys.

Just a quick note... v2.0.0 better than 2.0? It's more semver and we're likely to use that third number, I think...

**Comment by kmike** [comment]
I've seen a convention where 2.0.0 is used for version numbers (i.e. git tags) while 2.0 is used for branch names. Not sure it matters for tqdm.

**Comment by hadim** [comment]
As you want. I let you release. What is fine for you guys is fine for me ! Great job all !

**Comment by lrq3000** [comment]
Yes, great job guys :) As you want about the version, I'm fine with both.

**Comment by lrq3000** [comment]
Let's use 2.0.0, it's indeed more semantic versioning, and it will be more easy to update with bumpversion and tools like that.

**Comment by lrq3000** [comment]
I've canceled all the previous Travis builds but the latest one (that's why it was taking so long). The latest will probably fail too, because:

F401 '__version__' imported but unused

I don't know what to do about it...

**Comment by lrq3000** [comment]
There's something odd here: on my local machine, flake8 doesn't say anything about an error, there's nothing. It appears only in the Travis builds. Is the configuration different?

**Comment by casperdcl** [comment]
Better. Any more changes @lrq3000 ?

**Comment by lrq3000** [comment]
Yes last one :)

**Comment by lrq3000** [comment]
Travis should be OK now. After the tests are finished, if noone object, I will upload to PyPi :)

I still fear a bit about the RST, I don't know if it's possible to test beforehand if it will show correctly.

**Comment by casperdcl** [comment]
Shows fine in github, ergo should be fine in pypi

**Comment by lrq3000** [comment]
Nope, I had another case where it was fine for any RST viewer I could use (including Github), but not for PyPi (it seems its RST library is quite old).

In fact, I have just found a great tutorial (actually a [rant against pypi vs rst](http://inre.dundeemt.com/2014-05-04/pypi-vs-readme-rst-a-tale-of-frustration-and-unnecessary-binding/)), and indeed there are errors, the README.rst needs a fix. I'm working on it.

**Comment by lrq3000** [comment]
Ok, it was just a missing space between a "code" block and the actual code... The error message was quite unhelpful. Fixed it anyway, thank's to the [documentation](http://docutils.sourceforge.net/docs/ref/rst/directives.html#code).

Everything should be fine now. I will reversion to 2.0.0 (without dev) and upload to PyPi when Travis build is done.

**Comment by hadim** [comment]
+1111111

**Comment by lrq3000** [comment]
[Uploaded to PyPi](https://pypi.python.org/pypi/tqdm) :)

Only one glitch: the images are not showing, but we can update that without any problem normally.

**Comment by hadim** [comment]
```sh
$ pip install tqdm
Collecting tqdm
  Downloading tqdm-2.0.0-py2.py3-none-any.whl
Installing collected packages: tqdm
Successfully installed tqdm-2.0.0
```

Thanks again all !

**Comment by lrq3000** [comment]
Fixed the description :)

**Comment by lrq3000** [comment]
ARG you deleted! I just did an update lol. I'm going to do it on the main branch.

**Comment by hadim** [comment]
Oops :-(

**Comment by lrq3000** [comment]
I am also going to create a release, so that we have a reference point with the commit hash in case we need to git bisect in the future ;)

**Comment by lrq3000** [comment]
Travis build is all fine, release uploaded to PyPi and created here in Github Releases, everything's fine! Also, we have reached 100% coverage, both in statement coverage and _branch coverage_, which is amazing!

Great work everyone :)

**Comment by hadim** [comment]
I don't what happen to the master branch but historic has been modified (I have conflict with my local branch) and overall the version which has been uploaded to pypi does not exist anymore on the git history, same for the git 2.0.0 tag I guess.... not cool :-(

**Comment by hadim** [comment]
I guess we can live with that but be carefull next time and overall never force push on master !!!

**Comment by lrq3000** [comment]
@casperdcl rebased it to clean history. You can try to `git pull --rebase` to fix your issue, or else delete and reclone the whole project :/ Anyway, the 2.0.0 tag is still referencing the correct commit, so it should be OK.

**Comment by lrq3000** [comment]
Arg no you're right, it messed up the repo:

"lrq3000 released this an hour ago · 52 commits to master since this release"

Not cool... @casperdcl, do you think this is fixable?

**Comment by casperdcl** [comment]
yeah didn't realise you'd released already.

**Comment by hadim** [comment]
Well unless I am missing something git tag is for 4d7aac95 and this commit never shows in the master branch...

**Comment by lrq3000** [comment]
Yes @hadim, you're right, it points to a non existent reference now. We can still guess what was the history state because we still have the correct commit message, but the commit hash is pretty much useless now...

**Comment by casperdcl** [comment]
would clearing all tags and then tagging the last commit v2.0.0 work?

**Comment by hadim** [comment]
@casperdcl seems to be the only solution... please never force push in master again :-D

**Comment by hadim** [comment]
I let you do it ( @lrq3000 or @casperdcl )

**Comment by lrq3000** [comment]
Yes, I'm doing that since I have the builds

**Comment by lrq3000** [comment]
AH! well I have another solution: I can force push the entire history back since I still have it on my computer. But I don't know what is the most messy option between the two lol.

**Comment by hadim** [comment]
If you still have the correct history, please force push it !

**Comment by casperdcl** [comment]
Was really meant to be rebase (bviously incl force-push) on the tqdm2 branch. really was surprised that you merged it in.

**Comment by hadim** [comment]
Be sure the v2 tag hash is in your history

**Comment by hadim** [comment]
@casperdcl yeah its not only your fault here, I also totally forgot that you were rebasing... sorry for that

**Comment by hadim** [comment]
Next time we should first merge the PR, create the git tag and then upload to pypi (in that order).

**Comment by casperdcl** [comment]
nvm. i don't mind re-rebasing if you still have old history. obviously this time i'll leave in the appropriate commit... or we could just leave the messy history as is? idk.

I would think just re-tagging is best since it keeps the clean history?

**Comment by hadim** [comment]
Well I don't what's best, I let you decide with @lrq3000

**Comment by lrq3000** [comment]
Yes the old hash is in my history so normally I can recover the whole old history.

Seriously guys I don't know lol, I just have a bad feeling about the new history being rebased after releasing stuff and all, but I don't know, we can technically keep it.

**Comment by hadim** [comment]
Well seems weird to me too so let just not rebasing this time and keep the old and correct history no ?

**Comment by lrq3000** [comment]
I follow my intuition, I push back the old history and @casperdcl you push your new changes on top. We will be careful next time to rebase and do all git maintenance before releasing.

**Comment by hadim** [comment]
he cant rebase without re writing the history...

**Comment by lrq3000** [comment]
OK, old history restored. The release tag seems to be restored OK

**Comment by lrq3000** [comment]
Yes but he did some additional changes to RELEASE and some other stuff, that's what I meant

**Comment by hadim** [comment]
Ok it will go in the next release i guess

**Comment by lrq3000** [comment]
Yes anyway we can always make things better :) So we would never release if we waited the project to be perfect ;)

**Comment by kmike** [comment]
> We will be careful next time to rebase and do all git maintenance before releasing

Even better to do that before merging PRs. It seems this time we just had a really bad luck (quick rebase of merged PR), it wasn't anyone's error.

**Comment by casperdcl** [comment]
I'd rather say it was everyone's fault (incl. mine). I think we were all too eager having finally managed to contribute to the project proper. anyway nice work.

**Comment by lrq3000** [comment]
Yes we'll do better next time :) The release is good enough, it will be better next time, but I'm already quite glad the project reached this stage of maturity.

**Pull request merged**
