### PR TITLE
Drop support for EOL Python 2.6 and 3.3

### PR DESCRIPTION
**Pull request by hugovk**
Python 2.6 and 3.3 are EOL and no longer receiving security updates: https://en.wikipedia.org/wiki/CPython#Version_history

They're also little used.

Here's the pip installs for tqdm from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.5            |   50.6% |        228,303 |
| 2.7            |   28.6% |        129,062 |
| 3.6            |   16.0% |         72,107 |
| 3.4            |    4.1% |         18,633 |
| 3.7            |    0.3% |          1,136 |
| 3.3            |    0.2% |          1,020 |
| 2.6            |    0.2% |            773 |
| 3.2            |    0.1% |            490 |
| None           |    0.0% |              3 |

Source: `pypinfo --start-date -47 --end-date -17 --percent --pip --markdown tqdm pyversion`

Dropping them allows some old code to be removed, and more modern features of Python to be used. It also speeds up Travis builds.

This also adds `python_requires` to setup.py so pip knows which version to install for which Python version.

### CODE REVIEW

**Comment by casperdcl** [comment]
Thanks for this, but we'll probably only merge this once (if) `pip` drops support for python2.6... For now there are still people who could find wider support useful.

**Comment by hugovk** [comment]
Current pip 9 deprecates Python 2.6 support, next pip 10 won't support it. 

https://github.com/pypa/pip/issues/3955

**Comment by casperdcl** [comment]
yes but earlier versions of `pip` still work, and some old servers are tied to python2.6. Many other widely used packages still support 2.6. I don't feel we should be force-removing 2.6 support unless 1) we come across a new feature which really requires dropping support or 2) pip web API completely denies python 2.6 requests (unlikely any time soon)

**Comment by hugovk** [comment]
Rebased on master to keep current, and upgraded Python syntax using [pyupgrade](https://github.com/asottile/pyupgrade).

---

July stats show 2.6 downloads are down by ~65% and 3.3 by ~75% since December:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  39.05% |        165,991 |
| 3.6            |  37.27% |        158,403 |
| 3.5            |  17.79% |         75,594 |
| 3.7            |   3.20% |         13,616 |
| 3.4            |   2.50% |         10,638 |
| 3.3            |   0.06% |            273 |
| 2.6            |   0.06% |            269 |
| 3.2            |   0.04% |            190 |
| 3.8            |   0.01% |             56 |
| None           |   0.00% |              1 |
| Total          |         |        425,031 |

Source: `pypinfo --start-date 2018-07-01 --end-date 2018-07-31 --percent --markdown tqdm pyversion`

**Comment by jeking3** [comment]
There shouldn't be a need to delay this PR.  If folks are using older versions of Python they can add a limiter to their requirements to make sure they don't pull in a version that no longer supports it.

**Comment by hugovk** [comment]
And the purpose of `python_requires` (https://github.com/tqdm/tqdm/pull/502/commits/eb69dec2f31aa325a80defa797789c275c7d00e9) is so pip only installs the version of a package that declares support for the running Python.

**Comment by casperdcl** [comment]
but `tqdm` does support these EOL versions. The only reason to merge this PR is if there's another PR that was incompatible with py26/33.

**Pull request closed without merging**
