### PR TITLE
fix the problem #299 in terms of using tqdm in pandas

### PR DESCRIPTION
**Pull request by chengs**
0. update the branch.
1. Add new test cases about pandas
2. Solve the problem of #299, which is try to: find the correct "total" when using progress_apply and other functions in pandas.

#299 partially achieved its goal. With forbidding *args, one can get correct axis now, and use it to get the total (as number of iterations in progress_apply) (hereby a bug in #299 has been fixed).

However, however, however, pandas sometimes runs several more iterations to optimize its self. For example, in dataframe.progress_apply(func). 

-  if func is a numpy.ufunc or is very slow, then it will be executed `total` times.
- but if it is very quick or in some other cases, it will be executed `total+1` or `total+shape[axis0]` times.

I think, there is no need to adjust such particular pandas implementation, so in the wrapper function, I write
```python
def wrapper(*args, **kwargs):
                    # update tbar correctly
                    # it seems pandas apply calls func twice on the first column/row 
                    # to decide whether it can take a fast or slow code path.
                    # so stop when t.total==t.n
                    t.update(n=1 if t.total and t.n < t.total else 0)
                    return func(*args, **kwargs)
``` 
if if total is achieved, tbar will not be updated.

### CODE REVIEW

**Comment by chengs** [comment]
maybe I shall rebased and direct commit to master?

**Comment by casperdcl** [comment]
Thanks @chengs , yes, please do rebase on master

**Comment by chengs** [comment]
@casperdcl OK. I close this and create a new #524

**Comment by casperdcl** [comment]
you could've rebased this branch and force pushed instead of opening another PR, but nevermind now

**Pull request closed without merging**
