### PR TITLE
GUI

### PR DESCRIPTION
**Pull request by casperdcl**
Addresses #28.
~350it/s overhead when enabled with `gui=True`.
Looks promising but still needs testing and tidying.

### CODE REVIEW

**Comment by casperdcl** [comment]
Any idea why `py32` coverage/test build is failing on travis but all the rest passes?

**Comment by casperdcl** [comment]
erm... @hadim , @kmike any ideas on the weird Travis fail?

**Comment by hadim** [comment]
It's weird cuz only happenning on py32... can you try to relaunch Travis to see if it reproduces again ?

**Comment by lrq3000** [comment]
I think I had the exact same bug on two of my other projects. This is due to Travis which has recently updated to coverage 4, and this weirdly produces a bug, but only with Python 3.2 (not with other below or greater Python versions).

To fix this, you just need to add a statement to load coverage < 4 in your travis config.

**Comment by lrq3000** [comment]
Here's the Travis issue ticket:

https://github.com/travis-ci/travis-ci/issues/4866

Proposed fix by ZuluPro (which worked for me), in .travis.yml, add this:

install:
    [other instructions here...]
    - pip install 'coverage<4'

**Comment by lrq3000** [comment]
And BTW nice work here, I didn't try it for myself, but if the overhead is so small when using the GUI option, it's really amazing!

**Comment by casperdcl** [comment]
thx @lrq3000 ... if you have `matplotlib` you can easily checkout this branch and test it with the scripts in the `examples` folder.

**Comment by lrq3000** [comment]
Ah nice to know that there's a simple example to use @casperdcl :) I'll try that when I have some time (I'm a little bit overwhelmed by projects currently, and that's an understatement :( ).

**Comment by hadim** [comment]
@casperdcl I guess you want to merge this before we made the transition.

**Comment by lrq3000** [comment]
The workaround didn't work, coverage 4 is still used:

py32 installed: coverage==4.0,coveralls==1.0,docopt==0.6.2,nose==1.3.7,requests==2.8.0,tqdm==1.0,wheel==0.24.0

**Comment by lrq3000** [comment]
I think that you need to put it before installing coveralls, at least that's what I did in my other project, because I guess else installing coveralls will automatically install the dependencies such as coverage.

Please try this:

install:
   - pip install 'coverage<4'
   - pip install tox coveralls

**Comment by kmike** [comment]
It should be changed in https://github.com/tqdm/tqdm/blob/master/tox.ini. Btw, I think we can remove coveralls from tox.ini

**Comment by lrq3000** [comment]
@kmike ah maybe you're right, I didn't make a specific tox config in my other project, so the fix in .travis.yml was enough for me.

**Comment by casperdcl** [comment]
Ok. Third forced update later... should work now

**Comment by hadim** [comment]
Looks like it will pass :-)

**Comment by lrq3000** [comment]
Seems all good :)

**Comment by hadim** [comment]
:

**Comment by casperdcl** [comment]
wth that took a while -.- I was so freaked out by the bug but couldn't believe the latest version of `coverage` would break... On my scientific install (py27) coverage4 throws up a unicode-related error. not. cool.

**Comment by hadim** [comment]
Nice work dude !

**Comment by casperdcl** [comment]
i also recently found a bug in matlab's cuda-related linux libraries. that was even more not cool. ;) hope you guys can work out a way of using this in things like gooey (haven't looked at its source)

**Comment by lrq3000** [comment]
Yes it's very not cool when the libraries are broken :(

**Comment by lrq3000** [comment]
About Gooey integration, here's a starting point:

https://github.com/chriskiehl/Gooey/pull/120

The problem is that we'd need to directly modify Gooey in order to support integration of tqdm. Another way is to make Gooey able to callback to get progress updates, but this seems problematic according to the main developper:

https://github.com/chriskiehl/Gooey/issues/60

**Pull request merged**
