### PR TITLE
Add console parameter to rich wrapper

### PR DESCRIPTION
**Pull request by glensc**
Fixes https://github.com/willmcgugan/rich/issues/1766 

See also discussion:
- https://github.com/Textualize/rich/discussions/1765

Needed by:
- https://github.com/Taxel/PlexTraktSync/pull/663

### CODE REVIEW

**Comment by glensc** [comment]
@casperdcl can you move this forward?

**Comment by glensc** [comment]
@casperdcl can you include this in the new version?

**Comment by casperdcl** [comment]
Ah sorry for the delay :)

**Comment by glensc** [comment]
@casperdcl can you include this in next release please?

**Comment by casperdcl** [comment]
thanks for pinging and sorry for the delay!

How about #1311 for more generic compatibility? i.e. `tqdm.rich.tqdm(..., options={'console': True})`

**Comment by glensc** [comment]
I don't understand #1311 changes, also seems to be titled as 4.63.2 release notes, also console is not boolean, but an instance created elsewhere.

you can see the usage of this PR with the PR referred in PR body:

> Needed by:
> - https://github.com/Taxel/PlexTraktSync/pull/663

more particularly just this commit:
- [Taxel/PlexTraktSync@`19297cd` (#663)](https://github.com/Taxel/PlexTraktSync/pull/663/commits/19297cdef93097bb283d14df8219ac38a83edf48)

**Comment by casperdcl** [comment]
Right so from  [Taxel/PlexTraktSync@`19297cd` (#663)](https://github.com/Taxel/PlexTraktSync/pull/663/commits/19297cdef93097bb283d14df8219ac38a83edf48) you could do:

`partial(tqdm.rich.tqdm,  options={'console': plextraktsync.console.console})`

**Comment by glensc** [comment]
Uh ok. either way is fine probably.

**Pull request closed without merging**
