### PR TITLE
disable automatically on non-TTY

### PR DESCRIPTION
**Pull request by danielpanteleit**
When running python scripts that use tqdm in cron jobs; i noticed that the output of tqdm is also redirected. I changed the `disable` parameter, so if it is not set explicitly, the output will be disabled automatically if the output file is not a TTY (i.e. is some sort of redirection).

### CODE REVIEW

**Comment by lrq3000** [comment]
Hmmm I'm hesitant about this. Outputting to a non-TTY might be wanted, for example I'm not sure that a jupyter notebook would be detected as a tty. Also the output might be wanted in a log.

So this needs to be further tested on various environments before merging, we should be careful about this. If it can't be merged, we could add this as an example use case in the README.

**Comment by danielpanteleit** [comment]
I changed the default for `disable` back to `False`. Now you can set it explicitly to `None` to make it auto-detect TTY and disable it on non-TTY. This way there won't be any problems for existing code using tqdm.

We could think about using some constant like `tqdm.AUTO` instead of `None` though if you want.

**Comment by lrq3000** [comment]
@danielpanteleit Thank's a lot, you even made the unit tests, so I'm merging this right in!

Self note: this will maybe have to moved to tqdm_auto #234 when (if ever) it will be done, but meanwhile this will solve some issues.

**Comment by casperdcl** [comment]
thanks @danielpanteleit feel free to 👍 [this link](https://github.com/vinta/awesome-python/pull/662)

**Pull request merged**
