### PR TITLE
cleanup doc re: postfix

### PR DESCRIPTION
**Pull request by MPagel**
documents the availability of {postfix} for the bar_format string and distinguishes where postfix is a string vs dict. Also contrasts postfix behavior from desc/prefix behavior a bit more.

Adds set_postfix_direct method which allows for a keyless value to be added.

Augmentation for
#266 & #270 

- [x] add to docstrings
- [x] sync with README
- [x] add set_postfix_str()
- [x] add set_description_str() to address #347 
- [x] unit tests

### CODE REVIEW

**Comment by casperdcl** [comment]
from #347, I prefer @w1th0utnam3's suggestion of moving `": "` to the format string, which should remove the requirement for `set_description_str()`

**Comment by casperdcl** [comment]
any opinions, @MPagel @lrq3000 @w1th0utnam3?

**Comment by MPagel** [comment]
My point for set_description_str was to allow for the display of information without including a "key". Previously postfixes were constrained to displaying both the key and value of each dict item and did not allow for the display of just a string.

**Comment by casperdcl** [comment]
It's been a while sorry. I think @MPagel you might be getting confused between `set_description_str` and `set_postfix_str`?

**Comment by MPagel** [comment]
You are correct. My apologies.

**Comment by casperdcl** [comment]
The slightly annoying thing about moving this to the format string is the simple case of `tqdm(range(10))` will print a leading ` :` despite having no description. The only clean work-around I can think of is automatically removing `{desc} :` from the start of the format string if `desc` is empty.

**Comment by MPagel** [comment]
[fail] 11.74% tests_tqdm.test_format_meter: 0.0666s
[fail] 0.27% tests_tqdm.test_set_description: 0.0016s

Set description obviously fails because the procedure no longer exists. Format meter may fail as certain edge cases may have different output now....needs verification though.

**Comment by MPagel** [comment]
(travis-ci build failed due to failure on their end - prior to execution of tests)

**Comment by matanster** [comment]
A bit confused by the comments trail, I wonder if dropping the default colon from the description has been introduced in any version of the library. I.e. that when we set a description using `set_description` we won't get a colon added on the progress bar line right after the string that we set. Thanks in advance!!!

**Comment by casperdcl** [comment]
you can use `bar_format` to get exactly the effect you want. (e.g.: `bar_format='hello{percentage:3.0f}|{bar}{r_bar}'`)

**Comment by casperdcl** [comment]
or use `set_description_str()`

**Pull request merged**
