### PR TITLE
tqdm.contrib.concurrent.process_map: Add 'chunksize' argument

### PR DESCRIPTION
**Pull request by jonashaag**
Allow to set ProcessPoolExecutor.map 'chunksize' argument and provide
sane default value if unset.

- [x] I have marked all applicable categories:
    + [ ] exception-raising fix
    + [ ] visual output fix
    + [ ] documentation modification
    + [x] new feature
- [x] If applicable, I have mentioned the relevant/related issue(s)

Less important but also useful:

- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

### CODE REVIEW

**Comment by casperdcl** [comment]
I like this but on the other hand I'm not sure if we should on principle patch defaults. Surely there's a reason `concurrent.futures.ProcessPool.map` itself doesn't do this?

**Comment by jonashaag** [comment]
Yes I'm not sure it's a good idea either.

I  guess we're on the same page that adding the `chunksize` parameter without changing its default is a good idea?

As an alternative to selecting the chunksize parameter in the code, we could at least warn the user if they have a very large iterable (say, >10k items) that this will probably be much slower than necessary unless they set `chunksize` to a sensible value? I.e.  if `chunksize` is unset and there exists a large iterable in `iterables`, show a warning.

**Comment by casperdcl** [comment]
Exposing the param definitely sounds good.

**Comment by jonashaag** [comment]
Ok, I'll wait for your feedback on the warning thing and then update the patch.

**Comment by jonashaag** [comment]
Changed so that it warns when chunksize is unset and there exists an iterable with len >= 1000.

**Comment by casperdcl** [comment]
Following up @jonashaag about some things:

> almost entire rewrite of the code ... incl. things like format() -> % formatting, changing error message and comment wording

There were a few issues which needed sorting, including failing tests. The changes are all in https://github.com/tqdm/tqdm/pull/912/commits/3d39fde2f5fc3fd0467a1dc96b3c5bd440b73024

Summary:

- use `TqdmWarning` instead of `RuntimeWarning` to make it easier for users to filter out/suppress
- reorder imports alphabetically
- re-add and add missing developer documentation for internal helper `_executor_map`
- fix line lengths/formatting according to `flake8` tests
- remove backticks from `[default: ...]` notation (consistent with the rest of the code - should always be `eval()`able which excludes backticks)
- shorten & reword comments
- use `%` instead of `format` as it's faster and more readable for simple cases
- use `> 1000` rather than `>= 1000` - again as a very minor performance benefit and for brevity
- `SkipTest` on `ImportError` rather than `sys.version_info`

Note that I added a commit on top of yours so your commits will still show up in https://github.com/tqdm/tqdm/graphs/contributors after the next release. Also things like reordering lines won't affect your SLoC when using things like [`git fame -wMC`](https://github.com/casperdcl/git-fame/).

There's a lot of guidance in [CONTRIBUTING.md](https://github.com/tqdm/tqdm/blob/master/CONTRIBUTING.md) but do suggest improvements.

**Pull request merged**
