### PR TITLE
fully abstracted gui

### PR DESCRIPTION
**Pull request by casperdcl**
addresses #32

### CODE REVIEW

**Comment by casperdcl** [comment]
Can't currently think of a way to allow for backward-compatibility (i.e. need to drop `gui` argument from public interface)... will need to bump to v3.0.0 if no reasonable workaround exists

**Comment by lrq3000** [comment]
I have moved tqdm_gui to its own python script, I think it will be easier to maintain. Normally this move shouldn't have changed the performances of the GUI, but please check it on your workstation to see if there's no performance drop compared to your initial PR.

**Comment by lrq3000** [comment]
So, about retrocompatibility, indeed I don't think we can do this cleanly. In fact there is one way to do that: by making _tqdm an abstract class, and implementing the real code in another class. Then, tqdm(gui=True) would automatically overload tqdm_gui, or tqdm_console.

But I think that's probably not necessary, the gui was a pretty recent addition, so changing it now wouldn't be a big deal (ie, the people that already use the gui are still working on their scripts so they can update to use tqdm_gui instead).

**Comment by lrq3000** [comment]
Alright! All tests passed and coverage is 100%. For me, this branch is ready to be merged :)

**Comment by casperdcl** [comment]
Yeah I was looking into an abstract class solution and think it's not very pythonic... Just rebase, will merge this as v3.0.0

**Comment by casperdcl** [comment]
Hmm coveralls-related statistics submission errors.

**Comment by casperdcl** [comment]
... which miraculously just fixed themselves -.-

**Comment by lrq3000** [comment]
It was because of cosmic rays! lulz

**Pull request merged**
