### PR TITLE
fix nested + leave completed cursor placement

### PR DESCRIPTION
**Pull request by lrq3000**
Example usage:

```
from tqdm import trange
from time import sleep
lv = True
ns = True
for i in trange(2, desc='outer0 loop', leave=True, nested=4):
    for j in trange(3, desc='inner1 loop', leave=lv, nested=ns):
        for k in trange(4, desc='inner2 loop', leave=lv, nested=ns):
            for l in trange(100, desc='inner3 loop', leave=lv, nested=ns):
                sleep(0.005)
```

Need to:
- [x] Fix unit test for 100% coverage
- [ ] rebase and fix conflicts

### CODE REVIEW

**Comment by casperdcl** [comment]
hmm I like the simplicity of this fix. better than the dispatcher, I think.

**Comment by lrq3000** [comment]
Ok thank's @caspercl :) I will fix the coverage tomorrow.

2015-12-20 18:28 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by lrq3000** [comment]
Fixed unit test and updated documentation. Ready to merge :)

**Comment by lrq3000** [comment]
@casperdcl could you please tell me how you amend to add "bump version" message and then push to the master without creating a new branch to do that? Everytime I try, it rejects me because the master branch is protected now (which is good).

**Comment by casperdcl** [comment]
Oh @lrq3000 you should be able to first merge master into this branch, fix conflicts, then push to this branch. Once all checks pass you should be able to merge the PR into master from here

**Comment by casperdcl** [comment]
I'll temporarily unprotect master and rebase the ugly commit tree since the last release once this PR is fixed

**Comment by lrq3000** [comment]
Ok @casperdcl , I thought I should never merge a PR from github's web interface, but I understand that if I do the merge manually, there won't be any ugly merge message aftewards :)

About the `leave=False` issue, I couldn't find it, it seems everything is running smoothly for me. I'm going to add a unit test for that. Could you please give me a code snippet to reproduce your issue? Here's mine:

```
from tqdm import trange
from time import sleep
lv = False
ns = True
for i in trange(2, desc='outer0 loop', leave=True, nested=4):
    for j in trange(3, desc='inner1 loop', leave=lv, nested=ns):
        for k in trange(4, desc='inner2 loop', leave=lv, nested=ns):
            for l in trange(100, desc='inner3 loop', leave=True, nested=ns):
                sleep(0.005)
```

Result:
```
outer0 loop: 100%|###############################| 2/2 [00:12<00:00,  0.16it/s]

inner3 loop: 100%|##########################| 100/100 [00:00<00:00, 198.50it/s]
C:\git\rfigc\tqdm>
```

**Comment by lrq3000** [comment]
The latest commit should fix all issues with leave and nested.

**Comment by casperdcl** [comment]
well I was referring to the blank lines (2 between outer0 and outer3 in your example). Would be nice to somehow delete them.

**Comment by lrq3000** [comment]
Ah I see, well, I don't think that's possible to do with our decentralized approach to nested printing, each bar has no knowledge of how many other bars there are out there, so it can just print on its own line and give the hand to the parent bar, that's why they are left in place. Personally, I prefer that the bars stay at the same place after leave, so this issue doesn't bother me :)

**Comment by lrq3000** [comment]
To fix this issue and #87, we would need to use a centralized approach, the dispatcher concept. This would allow us to have total positionning control, just like in a curses environment. Of course, this flexibility will cost in terms of performance.

**Comment by lrq3000** [comment]
Closing this PR, see new approach in #87. We should delete this branch after the other PR gets merged.

**Pull request closed without merging**
