### PR TITLE
Inheritability

### PR DESCRIPTION
**Pull request by casperdcl**
Supports #77

### CODE REVIEW

**Comment by lrq3000** [comment]
Good job @casperdcl :) However, are we sure the closure variable `last_printed_len` won't get shared between all tqdm instances? Is this ok?

**Comment by lrq3000** [comment]
And why a `classmethod` and not a `staticmethod` ? (Maybe a staticmethod would be more efficient)

**Comment by casperdcl** [comment]
It works as expected (I tested, plus the unit tests have certainly tested). Don't know why I didn't use a `staticmethod` in the first place, though. changed it now :)

**Comment by lrq3000** [comment]
Great work :+1: 
I'll add a note in the readme on how to subclass tqdm with a short example.

**Comment by casperdcl** [comment]
well - you can always just point people to `tqdm_gui` ;)

**Pull request merged**
