### PR TITLE
Negative Updates raise error

### PR DESCRIPTION
**Pull request by casperdcl**
migrated from #110

### CODE REVIEW

**Comment by casperdcl** [comment]
hmm hard to tell whether the build is failing due to the recent Travis bug or something else...

**Comment by lrq3000** [comment]
Ill take a look at it later.
Le 20 Jan. 2016 20:48, "Casper da Costa-Luis" <notifications@github.com> a
écrit :

**Comment by lrq3000** [comment]
I think i found the issue but cannot test. It should be because you need to
use assert_raises to catch an exception reliably in a unit test, else this
may slip and be caught by nose first, which will consider it to be a
program error, not a test.

**Comment by casperdcl** [comment]
I thought travis was failing on installing/setting up the env (unicode chars in pip or something).

**Comment by lrq3000** [comment]
From the error displayed by Travis, it rather seems like the error is about
an uncaught exception (and indeed I checked in the code, we should fix that
anyway).

About the unicode bug, if you talk about the other issue, it only affects
the PR, but not our current codebase (this is because the other guy fixed
the unicode bug on Windows, but this in turns created a bug in Linux, so
I'll see how to fix that later on since I have Windows at disposal).

2016-01-21 22:29 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Pull request merged**
