### PR TITLE
tests: replace nose => pytest

### PR DESCRIPTION
**Pull request by pgajdos**
First attempt.

### CODE REVIEW

**Comment by pgajdos** [comment]
@casperdcl, are you interested in this pullrequest? I have to resolve lot of conflicts now, so I would like to ensure the time is effectively spent.

**Comment by casperdcl** [comment]
@pgajdos sure, I finally reviewed and overhauled some of the tests in the last couple of releases but don't intend on making any more major changes so you can fix conflicts now :)

**Comment by pgajdos** [comment]
@casperdcl okay, I will try to look at it this week again. Are you fine with the overall concept?

**Comment by pgajdos** [comment]
.

**Pull request closed without merging**
