### PR TITLE
Clarify pandas and tqdm_notebook notation

### PR DESCRIPTION
**Pull request by watercrossing**
In response to #473, I propose clarifying the documentation.
It is not:
`tqdm.pandas(tqdm_notebook)`, 
but 
`tqdm_notebook().pandas()`.

### CODE REVIEW

**Comment by chengs** [comment]
@casperdcl any update?

**Comment by chengs** [comment]
I think there is not an elegant way to do it...

**Comment by casperdcl** [comment]
I think this PR is a bit wrong. It should be `tqdm.tqdm.pandas()`, not `tqdm.tqdm().pandas()`

**Comment by chengs** [comment]
@casperdcl eh, you're right about ``tqdm``, while for ``tqdm_notebook``, must be called as a function, like ``tqdm.tqdm_notebook().pandas()``, otherwise it will be an error reported.

**Comment by casperdcl** [comment]
ah mentioned in #419 (and #177 -> #192) you need

```
from tqdm._tqdm_notebook import tqdm_notebook

tqdm_notebook.pandas(...)
```

This will hopefully change soon to:

```
# force notebook: from tqdm.notebook import tqdm
# or auto-detect notebook/CLI
from tqdm.autonotebook import tqdm

tqdm.pandas()
```

Maybe I won't wait for v5 to do this.

**Comment by casperdcl** [comment]
closed by https://github.com/tqdm/tqdm/commit/97a93932742db9e2c38672219a0aef8d1b3ad482

**Pull request closed without merging**
