### PR TITLE
Paper: Update impact stats for 2020

### PR DESCRIPTION
**Pull request by hugovk**
- [ ] I have marked all applicable categories:
    + [ ] exception-raising fix
    + [ ] visual output fix
    + [x] documentation modification
    + [ ] new feature
- [ ] If applicable, I have mentioned the relevant/related issue(s)

Less important but also useful:

- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

---

Not updated:

* "`tqdm` has accumulated over 20 million downloads [@pypi-downloads]"
   * How did you get this value? Would be good to update it.

* "7 thousand libraries [@lib-io]"
   * I don't see a count of libraries on https://libraries.io/pypi/tqdm, is it one of these?

### CODE REVIEW

**Comment by casperdcl** [comment]
- "7 thousand libraries" -> 13.1 thousand
- "20 million downloads" -> 101 million, vis https://packaging.python.org/guides/analyzing-pypi-package-downloads/

There's enough data that it's not possible to query in one go (exceeds free 1TB/month use) so here's what I have so far:

```yaml
    2015: 10957,  # 20151010 (v2.0.0) to 20151231
    2016: 574311,
    2017: 4910647,
    2018: 12973659,
    2019: 66707975,
    2020: 15762973  #  to 20200309
```

**Comment by hugovk** [comment]
> * "7 thousand libraries" -> 13.1 thousand
> * "20 million downloads" -> 101 million, vis [packaging.python.org/guides/analyzing-pypi-package-downloads](https://packaging.python.org/guides/analyzing-pypi-package-downloads/)

Thanks! I updated the years in the references for these.

> There's enough data that it's not possible to query in one go (exceeds free 1TB/month use) so here's what I have so far:
> 
> ```yaml
>     2015: 10957,  # 20151010 (v2.0.0) to 20151231
>     2016: 574311,
>     2017: 4910647,
>     2018: 12973659,
>     2019: 66707975,
>     2020: 15762973  #  to 20200309
> ```
> 
> Would appreciate if you could re-check the `2015`/`2016`/`2017` figures:
> 
> ```sql
> #standardSQL for 2015 from 10 Oct
> SELECT COUNT(*) AS num_downloads
> FROM `the-psf.pypi.downloads*`
> WHERE file.project = 'tqdm'
>   AND _TABLE_SUFFIX
>     BETWEEN "20151010"
>     AND "20151231"
> ```
> 
> ```sql
> #standardSQL for 2016
> SELECT COUNT(*) AS num_downloads
> FROM `the-psf.pypi.downloads*`
> WHERE file.project = 'tqdm'
>   AND _TABLE_SUFFIX
>     BETWEEN "20160101"
>     AND "20161231"
> ```
> 
> ```sql
> #standardSQL for 2017
> SELECT COUNT(*) AS num_downloads
> FROM `the-psf.pypi.downloads*`
> WHERE file.project = 'tqdm'
>   AND _TABLE_SUFFIX
>     BETWEEN "20170101"
>     AND "20171231"
> ```

That's a lot of downloads! Unfortunately I'm also out of quota.

**Comment by lrq3000** [comment]
Thank you for the commands, here is what I get:

2015: 0 (probably a bug?)
2016: 673688
2017: 5105012

**Comment by lrq3000** [comment]
Updated 2020 figure (up to 03/06/2020): 44400926

For 2015, it still reports 0 for me, I don't know why.

**Comment by casperdcl** [comment]
ok so:

```yaml
    2015: 10957,  # 20151010 (v2.0.0) to 20151231, not visible any more
    2016: 673688,
    2017: 5105012,
    2018: 12973659,
    2019: 66707975,
    2020: 45967256  #  to 20200606
```

overall ~131M downloads so far; the missing 2015 figure doesn't make any difference.

**Pull request merged**
