### PR TITLE
add `dask` submodule

### LINKED ISSUE #278: Dask support
Dask itself has a basic progressbar, but tqdm is certainly better - so I made a basic wrapper:

``` python
from dask.callbacks import Callback

class ProgressBar(Callback):
    def _start_state(self, dsk, state):
        self._tqdm = tqdm_notebook(total=sum(len(state[k]) for k in ['ready', 'waiting', 'running', 'finished']))

    def _posttask(self, key, result, dsk, state, worker_id):
        self._tqdm.update(1)

    def _finish(self, dsk, state, errored):
        pass
```

Usage (the same as dask progressbar):

``` python
with ProgressBar():
    ... .compute()
```

Does it belong to `tqdm`, what to you think? Also, any further suggestions/improvements?

### PR DESCRIPTION
**Pull request by casperdcl**
based on `tqdm.keras`

- [x] add `tqdm.dask.TqdmCallback` (#1079, #279 <- #278)
- [x] document
- [x] test

Testing:

`pip install "git+https://github.com/tqdm/tqdm@dask#egg=tqdm"`

```python
from tqdm.dask import TqdmCallback
import dask.array as da

with TqdmCallback(desc="compute"):
    x = da.random.random((10000, 10000), chunks=(1000, 1000))
    y = x + x.T
    z = y[::2, 5000:].mean(axis=1)
    z.compute()
```

```python
from tqdm.dask import TqdmCallback
import dask.array as da

cb = TqdmCallback(desc="global")
cb.register()

x = da.random.random((10000, 10000), chunks=(1000, 1000))
y = x + x.T
z = y[::2, 5000:].mean(axis=1)
z.compute()
```

----

- fixes #278
- replaces/closes #279

### CODE REVIEW

**Comment by casperdcl** [comment]
@deschman from https://github.com/tqdm/tqdm/issues/278#issuecomment-783615449: do you mean the example code in the OP above doesn't work for you?

**Comment by deschman** [comment]
I mean to say that I have been testing the devel branch with the code below.

```python


import time

import dask
from tqdm.dask import TqdmCallback as ProgressBar

schedule = []

for i in range(5):
    schedule.append(dask.delayed(time.sleep)(i))

with ProgressBar():
    dask.compute(schedule)

```

This fails because Callback from dask 2021.2.0 does not have a pbar attribute.

**Comment by casperdcl** [comment]
interesting... I ran you code (ubuntu, `pip install -U "dask==2021.2.0" "git+https://github.com/tqdm/tqdm@dask#egg=tqdm"`) and can't see any error:

```
100%|██████████████████| 5/5 [00:04<00:00,  1.25it/s]
```

**Comment by deschman** [comment]
I stepped through this more slowly and found the problem. Below is a traceback that is handled without any message. During handling, TqdmCallback._finish is called, where self.pbar is not defined due to the handled error. Perhaps an update to requirements or better handling of this error would be helpful?

'''pytb

  File "c:\users\deschman\spyder-env\lib\site-packages\dask\local.py", line 436, in get_async
    start_state(dsk, state)

  File "c:\users\deschman\spyder-env\lib\site-packages\tqdm\dask.py", line 27, in _start_state
    self.pbar = self.tqdm_class(total=sum(

  File "c:\users\deschman\spyder-env\lib\site-packages\tqdm\notebook.py", line 240, in __init__
    self.container = self.status_printer(self.fp, total, self.desc, self.ncols)

  File "c:\users\deschman\spyder-env\lib\site-packages\tqdm\notebook.py", line 117, in status_printer
    raise ImportError(

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
'''

**Comment by casperdcl** [comment]
ah right. That's just Python's default traceback - always important to look for the first error :)

**Pull request merged**
