### PR TITLE
add contrib.discord: first Discord Bot!

### PR DESCRIPTION
**Pull request by casperdcl**
- [x] add `contrib.discord` (similar to `contrib.telegram`)
- [x] document
- [x] abstract common features with `contrib.telegram`
  + [x] fix lazy large memory usage and discard unsent messages

Steps to test:

- `pip install -U 'git+https://github.com/tqdm/tqdm@discord#egg=tqdm'`
- [create a discord bot (not public, no requirement of OAuth2 code grant, only send message permissions) & invite it to a channel](https://discordpy.readthedocs.io/en/latest/discord.html)
- copy the bot token & channel ID and paste below:

```python
from tqdm.contrib.discord import tqdm, trange
for _ in trange(
	int(1e8),
	token='THIS1SSOMETOKEN0BTAINeDfrOmD1SC0rd',
    channel_id=0246813579,
):
    # worst-case empty for-loop
    # still does ~6M it/s, i.e. overhead ~170 ns/it
	pass
```

Result:

image

### CODE REVIEW

**Comment by oohwooh** [comment]
Hi so I'm really glad I found this because it's exactly what I wanted for a project I'm working on, but I'm wondering if there's any reason you opted to use `disco-py` instead of `discord.py`? From my experience `discord.py` is much more reliable and better maintained, and it currently looks like there's an issue with Python 3.8 compatibility for `disco-py`
would you be opposed to me porting this to use `discord.py` instead? The libraries look to be structured similarly so it would probably be only a few code changes. 

Thoughts?

**Comment by oohwooh** [comment]
I take back what I said about it being an easy fix, just realized `disco` is synchronous and `discord.py` isn't. I'm not sure what a clean solution would be to overcome that. Looking into it

**Comment by casperdcl** [comment]
Apart from the `async` issue and need to mess with mainloops, `discord.py` is also py3 only; whereas `disco` works perfectly fine with `tqdm` on a lot of old py2 code.

Also as a matter of personal taste, `discord.py` seems to have an extremely unpythonic design which goes against what I try to do with `tqdm`.

I think both discord libs are maintained - I don't particularly care about how much - but I'd be very interested in why you say one is more **reliable** than the other. If `disco` really is unreliable then I'd probably prefer switching to just plain `requests` like with https://github.com/tqdm/tqdm/blob/master/tqdm/contrib/telegram.py

**Comment by casperdcl** [comment]
About the py3.8 issue, is it https://github.com/b1naryth1ef/disco/issues/178? It it similar to https://github.com/b1naryth1ef/disco/issues/107 (i.e. a `gevent` issue)?

**Comment by oohwooh** [comment]
Thanks for the quick response! I appreciate the insight.
Reliable probably wasn't the best choice of words, in hindsight. What I was trying to say with that is that the current issue with installing the package from pip seems to have been present for a while. I just managed to resolve that one by using a `constraints.txt` file to ensure `gevent` was installed with an up-to-date version, and after doing that `tqdm.contrib.discord` works as expected.

Totally understand the matter of personal preference, and given that I think it's very reasonable for this code to just stay as is, and then when the `gevent` issue eventually gets fixed the package becomes a bit easier to use.

**Comment by casperdcl** [comment]
hmm yes just posted https://github.com/b1naryth1ef/disco/issues/178#issuecomment-695830159. I might open another PR there. They merged in my last PR pretty quickly...

**Comment by casperdcl** [comment]
https://github.com/b1naryth1ef/disco/pull/183 hopefully makes things more *reliable* :)

**Pull request merged**
