### PR TITLE
Min update

### PR DESCRIPTION
**Pull request by casperdcl**
addresses #36

### CODE REVIEW

**Comment by lrq3000** [comment]
Ah I see you removed the `object` inheritance in tqdm, but then you added it back. I think I tried with and without, and IIRC, with `object` inheritance speeds up a bit the class. But I'm not so sure so you if you remove it, just make sure it doesn't slow things down.

**Comment by casperdcl** [comment]
Actually I think `object` appears in the actual code but not in the documentation for the v2.0.0 release. I just made it more consistent. I don't think it should make any difference, though.

**Comment by lrq3000** [comment]
Ah yes indeed, I didn't think it was necessary since the Readme is mainly meant to show how to use the class and its method, but OK with the change.

**Comment by casperdcl** [comment]
Really don't know whether this counts as "minor" or "patch" as far as semver is concerned. I had deliberately decided on the old method, can't think why now. Don't think this counts as a significant new feature so tending towards a patch bump...

**Comment by lrq3000** [comment]
Yes agree for the patch bump, it's not very significant, just a small change in features.

**Comment by casperdcl** [comment]
do I just alter tqdm/_version.py and merge the PR?

**Comment by kmike** [comment]
I think it is better to have a policy of changing version after merging PRs, not in PRs themselves. It will prevent conflicts between PRs, stale version bumps and incorrect version bumps.

**Comment by lrq3000** [comment]
I agree @kmike, we should bump version directly on the main tqdm branch and not in PRs, as to avoid merge conflicts. This will be easier to maintain both for mergers and for devs.

**Comment by casperdcl** [comment]
merged

**Comment by casperdcl** [comment]
Odd. Needed to first merge then rebase on master. github couldn't detect it the [usual way](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request)

**Comment by lrq3000** [comment]
That's weird, I don't know why you had to do that :/

2015-10-18 23:35 GMT+02:00 Casper da Costa-Luis <notifications@github.com>:

**Pull request merged**
