### PR TITLE
misc

### PR DESCRIPTION
**Pull request by casperdcl**
- safer `close()` methods in tests
- `maxinterval` handled properly
- docs
- structure & formatting

### CODE REVIEW

**Comment by casperdcl** [comment]
still needs fixing for py3

**Comment by casperdcl** [comment]
Any idea how to fix this? The `closing()` syntax doesn't seem to work on `tqdm()` itself on python3... Do we need to define our own `__enter__()` and `__exit__()` or is there a more elegant solution?

**Comment by casperdcl** [comment]
one workaround is 

```python
from contextlib import contextmanager

@contextmanager
def closing(thing):
    try:
        yield thing
    finally:
        thing.close()
```

but that's not a proper fix... if people use the normal closing syntax in their own code (`from contextlib import closing`) it'll fail

**Comment by lrq3000** [comment]
Sorry, no idea, I didn't even know about closing() before!

**Comment by casperdcl** [comment]
Well in py2.7 the closing form contextmanager would do essentially what my comment above says. apparently this was deprecated in py3:
https://docs.python.org/2/library/contextlib.html

**Comment by lrq3000** [comment]
Yes, I think we need to define __exit__() and __enter__(). I think this is the cleanest, most pythonic approach. Why are you reluctant?

**Comment by lrq3000** [comment]
Ah yes indeed, this has been deprecated, but because we can use the with statement directly. But I guess the same problem will arise: without `__exit__()` nor `__enter__()`, Python won't know how to handle tqdm with the `with` statement...

**Comment by lrq3000** [comment]
To keep compatibility with Python 2.7, you can maybe do something like this:

```
try:
    with tqdm(_range(3)):
        pass
    closing = lambda x: x
except Exception:
    from contextlib import closing

**Comment by lrq3000** [comment]
A good tutorial on how to define enter and exit (I don't know if the API changed since then, it's an old article): http://effbot.org/zone/python-with-statement.htm

**Comment by lrq3000** [comment]
Basically, it would be:

```
        def __enter__(self):
            # Nothing to initialize?
            return self
        def __exit__(self, type, value, traceback):
            self.close()
```

**Comment by casperdcl** [comment]
Haha I figured it out by reading all the docs for the different versions. Would've been quicker if I'd checked your new comments first :+1:

**Comment by lrq3000** [comment]
Haha, yes this also happened to me, this is because you tried to fix this issue on your own (which is a quality actually) ;) Great job on this, this is way cleaner to write unit tests!

**Comment by casperdcl** [comment]
Yeah it was nice how aiming to clean up StringIO led to introducing a new feature for `tqdm`... Can you think of how we could use it in my `urllib` reporthook example?

**Comment by lrq3000** [comment]
Um... I'm not sure it's possible to use that for the urllib example, because it uses a callback, and I don't think we can use the `with` syntax to enhance anything. The only thing that I can think of:

```
def my_hook(t):
    last_b = [0]

    def inner(b=1, bsize=1, tsize=None, close=False):
        if close:
            t.close()
            return
        t.total = tsize
        t.update((b - last_b[0]) * bsize) # manually update the progressbar
        last_b[0] = b
    return inner

# etc...
with tqdm(unit='B', unit_scale=True, leave=True, miniters=1,
                  desc=eg_link.split('/')[-1]) as progressbar:
    eg_hook = my_hook(t)
    # etc...
```

But this was also possible before (I just construct the tqdm object outside of the my_hook() function), so using `with` doesn't really add anything here... BUT, it's clearly more easy to instanciate a manually updateable progress bar like that (so that we now have two usage of tqdm: in `for/while` loops, and with `with` statement).

**Comment by casperdcl** [comment]
The new `with` syntax is better since you don't have to `close` explicitly... The example you gave above doesn't need the `close=False` and associated code anymore. I've updated it on master.

**Pull request merged**
