### PR TITLE
auto-snap

### PR DESCRIPTION
**Pull request by casperdcl**
Automate snap builds (partially #685)

### CODE REVIEW

**Comment by casperdcl** [comment]
@Saviq is there any way to run `snapcraft` in travis with the following file?
```yaml
name: tqdm
summary: A fast, extensible CLI progress bar
description: |
 https://tqdm.github.io
adopt-info: tqdm
grade: stable
confinement: strict
base: core18
parts:
  tqdm:
    plugin: python
    python-version: python3
    source: .
    parse-info: [setup.py]
apps:
  tqdm:
    command: bin/tqdm
```

Currently getting https://travis-ci.org/tqdm/tqdm/jobs/500617394#L819-L822:
```
launch failed: multipass socket access denied
Please check that you have read/write permissions to '/run/multipass_socket'
An error occurred when trying to launch the instance with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
```

**Comment by Saviq** [comment]
@casperdcl you can't run Multipass inside travis as this would mean nested virtualization, which they don't support.

Instead, you need to drive snapcraft manually through LXD, have a look at [our approach to this](https://github.com/CanonicalLtd/multipass/blob/9665c8673829683296ad0bfa2492346521df1030/.travis.yml).

**Comment by casperdcl** [comment]
Possibly silly question, but since travis supports docker - what about running snapcraft in a docker container? Is that a thing?

**Comment by Saviq** [comment]
@casperdcl would basically be the same like with LXD, you'd have to drive it manually. And once snapcraft does get LXD support, it would be much simpler to use. With docker, you'd be on your own.

**Comment by casperdcl** [comment]
Thanks @Saviq - not sure whether the work-around is worth the effort for me atm. Might just wait until it's fixed.

**Comment by casperdcl** [comment]
@Saviq is this now fixable because of https://github.com/snapcore/snapcraft/pull/2509?

**Comment by Saviq** [comment]
@casperdcl if you try the edge `snapcraft`, possibly.

**Pull request merged**
