### PR TITLE
support async generators

### PR DESCRIPTION
**Pull request by AlJohri**
replaces https://github.com/tqdm/tqdm/pull/91

### CODE REVIEW

**Comment by casperdcl** [comment]
Thanks. Could you write a unit test? Don't worry about py2 & unrelated failures on travis, I can fix that.

closes #91

**Comment by AlJohri** [comment]
@casperdcl Is it fine to use `async def` or should I use the `@coroutine` decorator instead to keep it backward compatible before Python 3.5?

**Comment by casperdcl** [comment]
backward compatible is best

**Comment by ekevoo** [comment]
Any plans to continue this?

**Comment by casperdcl** [comment]
@ekevoo (or anyone else) feel free tto take over

**Pull request closed without merging**
