### PR TITLE
pandas.Series.progress_map, update docs, tests

### PR DESCRIPTION
**Pull request by casperdcl**
addresses #214

### CODE REVIEW

**Comment by casperdcl** [comment]
Heck I just added:

-         Series.progress_apply
-         SeriesGroupBy.progress_apply
-         Series.progress_map
-         SeriesGroupBy.progress_map
-         DataFrame.progress_apply
-         DataFrameGroupBy.progress_apply
-         DataFrame.progress_applymap
-         Panel.progress_apply
-         PanelGroupBy.progress_apply
-         GroupBy.progress_apply
-         GroupBy.progress_aggregate
-         GroupBy.progress_transform
-         Panel.progress_apply
-         PanelGroupBy.progress_apply

I don't even know what half of those are but they seem to exist in documentation.

**Comment by casperdcl** [comment]
while we're at this, does anyone know how to `pip install pandas --only-binary pandas` or equivalent? basically want to get travis to install pandas quickly so it doesn't take ages to test. @lrq3000 @CrazyPython

**Comment by CrazyPython** [comment]
@casperdcl uhhh use a package manager like apt-get or homebrew? they usually have binaries

**Comment by lrq3000** [comment]
Great work @casperdcl ! That's amazing all the methods you added, pandas lovers will be very glad!

About installing pandas binaries instead of pip, we can maybe use condas on Travis instead:

http://conda.pydata.org/docs/travis.html

What is your estimation of the time we lose on Travis with pip pandas?

**Comment by lrq3000** [comment]
Also why was `tqdm_pandas` converted to a core classmethod `tqdm.pandas`? I initially thought it was to avoid the need to specify `tclass` as an argument (by using `self.__class__` or something like that instead), but it is still present?

**Comment by CrazyPython** [comment]
@lrq3000 

1. Travis right now is insanely slow for this project.

2. It's more pythonic

**Comment by casperdcl** [comment]
I tried miniconda for installing everything but pandas did not have
binaries so was compiled from source! I have re-enabled mutithread builds
so that roughly counteracts the increased time caused by installing.

**Comment by lrq3000** [comment]
Why is it more pythonic? Before it was like a decorator, isn't a decorator pythonic enough? The merge into the core lib made it more object-oriented for sure, but that's as pythonic as a decorator. The issue with merging into core `tqdm` is that it reduces modularity, and this is bad for two reasons:

1. It imposes a burden on core developpers who have to ensure that the core works correctly at all time and with any set of parameters, and we are currently only 2 regular contributors.

2. It imposes a burden on third-party submodules developpers because they have to ensure the compatibility of their module with `pandas` when they inherit from core `tqdm` (or they have to neutralize the `pandas` method which is a weird API for a modular architecture, having to neutralize things we do not want to implement).

**Comment by lrq3000** [comment]
Ok I checked the Travis log, indeed it takes about 3.6 minutes to build pandas (the total test time is 4.2 min...) so yeah we need to try to fix that.

I found [this link](http://sburns.org/2014/03/28/faster-travis-builds.html), I'm going to try it out.

**Comment by lrq3000** [comment]
I'm going to soon demodularize `tqdm.pandas()` back to `tqdm_pandas()` except if you don't agree guys. I thought about it and here are the reasons:

* Huge optional dependencies (pandas + numpy + whole lot of things) shouldn't be in core module.
* Still in alpha phase. Alpha/beta libs can change their API at anytime, and thus lead us into [software rot](https://en.wikipedia.org/wiki/Software_rot), whereas `tqdm` core design is without any third-party library to ensure total independence (which limits greatly software rot). Also, modularized extensions are easier to maintain in case of API change because we can make different plugins for different versions of the API. I think we should make a rule of thumb to never include an experimental library/code in the core module.

**Comment by casperdcl** [comment]
hmm. The dependencies aren't enforced if the function isn't used, @lrq3000.

**Comment by lrq3000** [comment]
@casperdcl I know but they are still optional dependencies in the core module. If the API ever changes, we will have to adapt the core module to fit the changes. I'm not here talking just from a technical run-time view (optional dependencies) but also from our developer view (core dependencies with required maintenance and support).

**Comment by lrq3000** [comment]
I mean, we can of course keep that in core, but then we need someone to explicitly be assigned to this support and we assume a shift in the library's design (everything can be put in the core).

**Pull request merged**
