### PR TITLE
replace nose => pytest

### PR DESCRIPTION
**Pull request by pgajdos**
`nose` will stop working with newer `python` versions.

### CODE REVIEW

**Comment by casperdcl** [comment]
replaces/closes #1045

**Comment by pgajdos** [comment]
@casperdcl what do you insist to fix from above failures? Everything? For example, I do not understand 'Method could be a function'. 'Missing function docstring' by inner()? It was not there even before. And 2.6 build?

Thank you for not leaving me alone ;).

**Comment by pgajdos** [comment]
I am also not sure with 'TestWithInstancesCheck', perhaps you would find better? And class and functions layout, is it ok?

**Comment by casperdcl** [comment]
Thanks @pgajdos ... will review later.

**Comment by casperdcl** [comment]
also fixed a py3 CLI bug when using `--delim` along with `--update` or `--update_to`

**Review by casperdcl — APPROVED** [review]
- also fixed a py3 CLI bug when using `--delim` along with `--update` or `--update_to`
- For later: use `capsys`/`capsysbinary` instead of all the painful `closing(*IO())`

**Comment by pgajdos** [comment]
Thanks!

**Pull request merged**
