### PR TITLE
add `tqdm.asyncio`

### LINKED ISSUE #65: Asynchronous tqdm
From Python 3.4, the stdlib provides an asynchronous decorator. Maybe this can be used to make tqdm asynchronous, thus lowering even further the overhead?

Eg,

```
try:
    from asyncio import coroutine
except ImportError:
    def coroutine(func):
        return func
```

From the excellent [ipy_progressbar module](https://github.com/aplavin/ipy-progressbar/blob/ipy2/ipy_progressbar/base.py).

Also, it's interesting to note that they used a `deque(maxlen=100)` to memorize all 100 previous `delta_t` to compute their eta. This is I think quite efficient (but not as efficient as us), and it can be a useful trick for us if we want to implement more complex etas.

### PR DESCRIPTION
**Pull request by casperdcl**
Would love to call this `tqdm.async` but unfortunately `async` is a reserved keyword.

- [x] choose a name: `asyncio` ~~`coroutine`, `asynchronous`, ...~~
- [x] support iterables
- [x] support async iterables
- [x] support coroutine.send
- [x] add `as_completed` wrapper
- [x] ~~add async context manager~~ why? don't see any use case (`async with tqdm() as t`?)
  + [x] ~~support async update~~ why? don't see any use case (`await update()`? lol...)
- [ ] confirm that there's no better/more correct way to wrap coroutines/async generators
- [x] test properly
  + [x] basic tests
  + [x] fix tests
  + [x] mock awaitables, etc...
- [x] add/update documentation
  + [x] inline
  + [x] readme
  + [x] `examples/` folder

Examples:

```python
import asyncio
from tqdm.asyncio import tqdm, trange
def count(start=0, step=1):
    i = start
    while True:
        new_start = yield i
        if new_start is None:
            i += step
        else:
            i = new_start
async def main():
    N = int(1e6)
    async for row in tqdm(trange(N, desc="inner"), desc="outer"):
        if row >= N:
            break
    with tqdm(count(), desc="coroutine", total=N + 2) as pbar:
        async for row in pbar:
            if row == N:
                pbar.send(-10)
            elif row < 0:
                assert row == -9
                break
    # should be under 10 seconds
    for i in tqdm.as_completed(list(map(asyncio.sleep, [1] * 10)),
                               desc="as_completed"):
        await i
```
```bash
asyncio.run(main())  # Python 3.7+
inner: 100%|███████████████| 1000000/1000000 [00:01<00:00, 928957.82it/s]
outer: 100%|███████████████| 1000000/1000000 [00:01<00:00, 928975.72it/s]
coroutine: 100%|██████████| 1000002/1000002 [00:00<00:00, 1483744.37it/s]
as_completed: 100%|██████████████████████| 10/10 [00:01<00:00,  9.97it/s]
```

---

- closes #772 (cherry-picked commits from @AlJohri)
- closes #91 (cherry-picked commits from @lrq3000)
- fixes #65

CC other participants: @Midnighter @sametmax @malarinv @Ekevoo 
CC :+1: reactors: @AdrienPensart @supermodo @lukaville @mikulas-mrva @WestXu @Scoder12 @malarinv

Disclaimer: I wrap C++ and/or CUDA anytime I need real concurrent speed, but don't use async Python much so don't know if I'm missing something. Feedback would be appreciated :heart:

### CODE REVIEW

**Comment by Midnighter** [comment]
I have one question about your design. If I understand your code correctly, `tqdm_asyncio` presents an asynchronous interface even for synchronous iterables. You went through some extra work to make that possible but is it desirable? I would be happy to use a different async progress class but it certainly is convenient to not have to care whether my iterable is async or sync.

**Comment by casperdcl** [comment]
> it certainly is convenient to not have to care whether my iterable is async or sync

yes exactly. This PR aims to address multiple issues for ease of use.

Also as I understand `async` and `coroutine` are actually two different things - there are differntly-implemented "coroutines" in python2, for example. Would this be of interest?

```python
from tqdm.auto import tqdm as tqdm_auto

def autonext(func):
    def inner(*args, **kwargs):
        res = func(*args,**kwargs)
        res.next()
        return res
    return inner

class tqdm_coro(tqdm_auto):
    @classmethod
    @autonext
    def pipe(cls, target, **tkwargs):
        """
        Python2 coroutine-style pipe.

        This:
            r = receiver()
            p = producer(r)
            r.next()
            p.next()
        Becomes:
            r = receiver()
            t = tqdm.pipe(r)
            p = producer(t)
            r.next()
            p.next()
        """
        with cls(**tkwargs) as pbar:
            while True:
                obj = (yield)
                target.send(obj)
                pbar.update()

def source(target):
    for i in ["foo", "bar", "baz", "pythonista", "python", "py"]:
        target.send(i)

@autonext
def grep(pattern, target):
    while True:
        line = (yield)
        if pattern in line:
            target.send(line)

@autonext
def sink():
    while True:
         line = (yield)
         tqdm_coro.write(line)

source(
    tqdm_coro.pipe(
        grep('python',
            sink())))
```

**Comment by Midnighter** [comment]
> Also as I understand async and coroutine are actually two different things - there are differently-implemented "coroutines" in python2, for example. Would this be of interest? Maybe just in documentation?

I don't have the bandwidth in my own projects so I started only supporting Python 3.6+. Looking at the classifiers on PyPI, you go as far back as supporting 2.6 which is pretty tough I think.

As far as I understood the topic so far, all asynchronous functions are coroutines. The syntax simply changed from the `@asyncio.coroutine` decorator to the (in my opinion) cleaner `async` keyword. It's possible that there are multiple implementations in Python 2 since asyncio only became widely useable in Python 3.5.

**Comment by casperdcl** [comment]
I'm talking about something which predates even `@asyncio.coroutine`.

In python2, the word coroutine referred to a type of generator obect driven by `send()` rather than `next()`, and had nothing to do with asynchronicity.

**Comment by Midnighter** [comment]
Thank  you for making this happening @casperdcl :slightly_smiling_face:

**Comment by casperdcl** [comment]
whew all done in `tqdm>=4.48.0` https://github.com/tqdm/tqdm/releases/tag/v4.48.0

**Pull request merged**
