### PR TITLE
Add ncols to specify tqdm_notebook bar width

### LINKED ISSUE #276: Specify `tqdm_notebook` bar width
Thanks to the maintainers for this incredible tool!

I'm wondering how to specify the width of a progress bar in a Jupyter notebook, since the default is pretty small. The `tqdm_notebook` function doesn't seem to respect the `ncols` or `dynamic_ncols` keyword arguments of `tqdm`. 

Is there a way to do this? If not, then I guess this is a feature request 😸

### PR DESCRIPTION
**Pull request by lrq3000**
Fixes #276 but does not work yet as layout seems to be broken in current ipywidgets (see https://github.com/ipython/ipywidgets/issues/773).

I tried using either `widget.layout.width = 100%` and `Layout(width='100%')`, and in either case `ipywidgets` raises an error saying that both are unknown property/can't import Layout class...

### CODE REVIEW

**Comment by lrq3000** [comment]
It should be fixed with the latest ipywidgets now :) Didn't try it yet though, if someone can confirm it works it would be great! (and it could be merged in!)

**Comment by chengs** [comment]
need some help? @casperdcl

**Comment by casperdcl** [comment]
always :) @chengs, feel free to fork, rebase this branch onto master, and open a PR

**Comment by casperdcl** [comment]
actually I just added you as a collaborator so you don't need to fork (just push to a new branch here)

**Comment by chengs** [comment]
It works, but there is a bug on style. I will fix it.

**Comment by chengs** [comment]
@casperdcl now it works, and I wrote some test, if they work on your side, I think it is ok to merge.
https://gist.github.com/chengs/0eeb86893c4fc8eba92c122ef8df550c

**Pull request merged**
