### PR TITLE
Reorder Travis dependencies install to fix numpy install

### PR DESCRIPTION
**Pull request by lrq3000**
Try to implement #272.

### CODE REVIEW

**Comment by lrq3000** [comment]
DO NOT MERGE THIS, there is the old monitoring thread squashed commit, I don't know how it got here.

**Comment by lrq3000** [comment]
All good to me.

**Comment by lrq3000** [comment]
Thank's for fixing the bad commit @casperdcl .

**Comment by lrq3000** [comment]
Ah no, not good, still need to exclude pandas and numpy for py26 and py33 tests. Normally the libs should be cached but seemingly it doesn't work on these python versions, so let's just skip.

**Comment by lrq3000** [comment]
Done and reduced duplication.

**Comment by casperdcl** [comment]
I wasn't too sure skipping them was a good idea so I left them in. but on second thoughts... all of these things are either not core tqdm or outdated, so I suppose this is fine.

**Pull request merged**
