### PR TITLE
Style fixes

### PR DESCRIPTION
**Pull request by casperdcl**
partially inspired by https://www.codacy.com/app/tqdm/tqdm

### CODE REVIEW

**Comment by lrq3000** [comment]
Nice, I validate. Nice finding, I like codacy, it's not too much invasive (it does not try to force us into a coding style, it just respects PEPs).

**Comment by lrq3000** [comment]
Also if you are using Chrome, there is the [Codecov extension](https://chrome.google.com/webstore/detail/codecov-extension/keefkhehidemnokodkdkejapdgfjmijf) to see code coverage results directly on github. That's faster and easier than navigating results through their website.

**Comment by lrq3000** [comment]
But Casper, please wait for a review next time before merging, even if this one was a quick one, the review system should not be bypassed as long as we are at least two on the project...

**Comment by casperdcl** [comment]
Thanks Stephen; thought you were going to be afk for a couple of weeks. Yes I agree we should review more (which is why I enabled the feature!)

**Comment by lrq3000** [comment]
Yes i am afk in the sense that i have minimal spare time to code new
features but i try to be always available to comment and review :)
Le 24 Oct. 2016 11:56, "Casper da Costa-Luis" <notifications@github.com> a
écrit :

**Pull request merged**
