### PR TITLE
CLI tidy

### PR DESCRIPTION
**Pull request by casperdcl**
better help messages and no docopt dependency for usage as a command-line module. Depends on #150

### CODE REVIEW

**Comment by lrq3000** [comment]
Wow I missed the train. Does `tqdm` support docopt now?

**Comment by casperdcl** [comment]
Lol I added some `docopt` style parsing logic natively. As I said, CLI pipe
execution for tqdm was something I've always intended to implement... And
I've stuck to strict formatting of the `__init__` help message precisely so
that 1) it looks nice in the readme with minimal effort, 2) it looks nice
in python's interactive help (76 char line limit) and 3) is parsable by
things such as docopt or (with this PR) a bit of regex. Lol.

**Comment by casperdcl** [comment]
I also take this opportunity to note [casperdcl/argopt](https://github.com/casperdcl/argopt) is very cool and helped me implement this PR.

**Comment by casperdcl** [comment]
In case you missed this too: `7z a -bd -r docs.7z ./docs | tqdm | wc -l`

**Comment by lrq3000** [comment]
Ok I see, very good work you did there Casper! I hope your argopt lib will get more known, that's really great (did you tell Gooey's author about it? They had issues with docopt support and dropped it recently but wanted to get it back, so maybe your lib can fill the gap?).

Yes I saw about the pipe, that's a great feature! Unluckily I cannot use it on Windows limited terminal :(

**Comment by casperdcl** [comment]
It works in git bash on windows, as well as the normal windows cmd...
Tested on both win7 and 8, 64bit, python2.7

**Comment by casperdcl** [comment]
@lrq3000 regarding argopt and Gooey, I opened https://github.com/chriskiehl/Gooey/pull/158 which is required to get Gooey working with argopt. The nice thing is docopt is not required at all there either.

**Comment by lrq3000** [comment]
Oh great, but I thought it did not because the unit test fails on my OS
(Windows7).

2016-04-24 18:01 GMT+02:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by casperdcl** [comment]
@lrq3000 just found out why the test fails:


``` python
# foo.py
import sys
for x in sys.stdin:
   sys.stdout.write(x)
```

And then:

``` sh
cat file_with_unix_line_endings | python foo.py > magically_dos_line_endings
```

**Comment by lrq3000** [comment]
Wow, nice finding @casperdcl, thank you for having a look. Since `sys.stdout.write()` should not output anything else than the characters it's fed, I guess it's the `>` operator that converts the newline returns. I don't know if there's a way to circumvent that, my guess is that this operator should be dropped and the writing to the file should be done via Python directly. Or we need a file line-by-line, so that newline returns are used as implicit separators.

**Comment by casperdcl** [comment]
I found that `sys.stdin` is a `file` object which defaults to *convert*
line endings to the native system's line ending conventions. such fun.
Easiest work-around is `.replace('\r\n', '\n')`.

**Pull request merged**
