### PR TITLE
#73: Restarting a progress meter without getting crazy

### PR DESCRIPTION
**Pull request by jcea**
As requested in #73

### CODE REVIEW

**Comment by casperdcl** [comment]
@lrq3000 did you have something more elegant than this in mind?

**Comment by lrq3000** [comment]
Yes I have another idea but it was before I saw this PR. If this fixes the ETA, then we can just merge, but I doubt that since it just sets `self.n = initial`, so I guess the ETA will still be flawed the first few iterations (it will consider that it has done `initial` steps in exactly 0 seconds!).

My idea was to implement one new method `tqdm.unpause(n=None)` to unpause and skip the time that has been spent between `last_print_t` and now, and `n` would be an optional to also skip n iterations (so unpause could be used at the start, but also in the middle of using tqdm). This should fix the ETA in any case by setting a new variable `self.t_offset = time.time() - self.last_print_t` and then subtract `self.last_print_t - self.t_offset` everywhere `self.last_print_t` is used.

**Comment by jcea** [comment]
The ETA is perfect because you initialize average with "None". So it works fine:

>>> a=tqdm.tqdm(total=10, initial=5); time.sleep(1); a.update()
 60%|██████████████████████████▍                 | 6/10 [00:01<00:04,  1.00it/s]

**Comment by lrq3000** [comment]
Ok good for me, sorry I didn't get it the first time I've read it :)

@casperdcl Before merging to master, should we move `initial` argument to last position to be retrocompatible?

**Comment by casperdcl** [comment]
merged in a rabase

**Pull request closed without merging**
