### PR TITLE
Wrapped monospacing around example progress bar

### PR DESCRIPTION
**Pull request by CrazyPython**
Looks better, more accurate representation of progress bar.

### CODE REVIEW

**Comment by lrq3000** [comment]
Thank's for the better formatting. We should then also remove the escapes because they aren't necessary anymore:

```76%\|████████████████████\             \| 7641/10000 [00:34<00:10, 222.22 it/s]```

**Comment by CrazyPython** [comment]
@lrq3000 boom! glad to help you out!

**Comment by casperdcl** [comment]
? does this work? I was sure in the past either github or pypi condensed spaces even in mono...

**Comment by CrazyPython** [comment]
@casperdcl huh?

**Comment by CrazyPython** [comment]
@casperdcl why hasn't `codecov/changes` finished building yet? :/

**Comment by CrazyPython** [comment]
Do the same in PyPI.

**Comment by CrazyPython** [comment]
@casperdcl why hasn't codecov completed yet? I think it's bugged. you should restart it and/or disable the requiredness of codecov. I don't think code coverage should ever block a PR.

**Comment by casperdcl** [comment]
merged in #212

**Comment by casperdcl** [comment]
I recall we added two different coverage methods because different people were comfortable with different ones. In the past I've also noticed interesting differences between the stats reported. each seems to have its advantages. just tried resetting the codecov hook. we'll see

**Pull request closed without merging**
