### PR TITLE
initial benchmark framework to visualise regression

### PR DESCRIPTION
**Pull request by casperdcl**
Requires the `asv` python package as suggested in #298 (installable via `pip`) and either `conda` or `virtualenv`.

``` sh
~/tqdm$ asv run v1.0.0..master  # all commits from tag v1.0.0 to current master
~/tqdm$ asv publish  # builds html
~/tqdm$ asv preview  # serves to http://127.0.0.1:8080/
```

Takes about 30min to run first time. Pushable to https://github.com/tqdm/tqdm/tree/gh-pages using `asv gh-pages`. See the result here: https://tqdm.github.io/tqdm/ (note: not the same as https://tqdm.github.io/).

### CODE REVIEW

**Comment by lrq3000** [comment]
Great work @casperdcl, that was very fast!

Ok so if I understand correctly, the tqdm perf are evaluated from the whole commit history, so this alleviates the issue of per machine perf bias. That's great! And it takes only 30 min!!!

Here are a few feedback (anybody can answer, not only @casperdcl):

1. The test should be run after #250 and #198 gets merged and with this command:

```
trange(int(1e8), miniters=None, mininterval=0.1, smoothing=0)
```

Against v1. See more info about why [here](https://github.com/tqdm/tqdm/pull/258#issuecomment-245119167). I expect to see a much smaller difference in perf, maybe even none (but the monitoring thread implies a 0.1 perf impact, but it can be disabled and then I expect to see really no difference with v1.0).

2. How is the gh-pages updated? I mean, if I do it on my own machine and try to upload, will my push be incremental (my result gets added after yours), or will my result file replace the old one altogether (thus we will lose your results since I never done an asv run on my machine)?

3. optional: I think we should time the relative time between normal iteration and tqdm iterations, like we do in perf test, this should be a more reliable metric (but that's an optional point since range is generated in the setup).

**Comment by casperdcl** [comment]
0) 30 min only the first time if you benchmark *all* commits from v1.0.0 onwards. Subsequently you shouldn't have to rerun tests provided your machine and background load is the same.
1) we should leave the no-arg case alone, and add more cases such as the one you mentioned.
2) you will overwrite with whatever is on your machine. if i send you my `tqdm/.asv/results` folder (or we version control it) before you run your tests then your results will get appended to it. Here you go:
[dot_asv_slash_results.zip](https://github.com/tqdm/tqdm/files/560871/dot_asv_slash_results.zip)
3) yes see (1)

**Comment by lrq3000** [comment]
Great for 0), this is a very good point for asv.

About 2) thank's, and yes it would be great to version control it (can't we version gh-pages directly?) but first we need to check whether it works correctly when reusing a report file generated on another machine (does asv have a mechanism to adapt the perf to the machine, eg by rerunning a few commits to see the diff with what was calculated in the report and subsequently scale the incremental results?). Because if the results are per machine anyway then it's useless to version control it, it's then better that everyone just generate his own report.

About 1) and 3) agreed.

**Comment by lrq3000** [comment]
This is exciting, this will help us track down performance drop a lot easier!

**Comment by casperdcl** [comment]
yes, it's per machine. I've updated and pushed relative tests https://tqdm.github.io/tqdm including the current master (v4.9.0 - though not yet tagged) so you can see the slight regression at the end

**Comment by lrq3000** [comment]
Yep the monitoring thread is clearly a burden, but the cost is worth if you ask me. But we should disable it in one test (the test with smoothing=0) to really test with minimal feature set similar to tqdm v1.0 to see if perf is the same.

**Comment by casperdcl** [comment]
#250 and #198 can no be rebased onto master and asv tests added within the respective PRs.

**Pull request merged**
