### PR TITLE
Minor tidy 2

### PR DESCRIPTION
**Pull request by MPagel**
remove misc calls to `format_meter`
replace with calls to `__repr__` - this will allow for greater future flexibility

Follow-up to e18f20497b4253e21174d4114b22559db3f612ec

### CODE REVIEW

**Comment by MPagel** [comment]
also you might be able to simplify `self.fp.write(self.__repr__())` call in refresh to be `self.fp.write(self)`

**Comment by casperdcl** [comment]
would be happy to review @MPagel if you want to rebase onto current master and fix conflicts

**Comment by MPagel** [comment]
should be good to go :)

**Comment by casperdcl** [comment]
thanks. will have a look tomorrow.

**Pull request closed without merging**
