### PR TITLE
Fix code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
This pull request fixes some of the code quality issues raised by DeepSource on my fork of this repository. I have fixed some issues using DeepSource's Autofix.

Take a quick look at all the issues caught by DeepSource for this repository [here](https://deepsource.io/gh/withshubh/tqdm/issues/?category=recommended).

### Summary of fixes

- Remove unnecessary comprehension
- Use literal syntax to create data structure
- Remove redundant `None` default

You can also have a look at the [configuration file](https://github.com/withshubh/tqdm/blob/master/.deepsource.toml) I used for DeepSource Analysis.

### CODE REVIEW

**Comment by casperdcl** [comment]
Thanks. A few questions:

1. what's the advantage of DeepSource over Codacy?
2. can the configuration be moved from `.deepsource.toml` to a `[tool.deepsource]` section under `pyproject.toml`?

**Comment by withshubh** [comment]
> Thanks. A few questions:
> 
> 1. what's the advantage of DeepSource over Codacy?
> 2. can the configuration be moved from `.deepsource.toml` to a `[tool.deepsource]` section under `pyproject.toml`?

Hey @casperdcl :wave: 
1. DeepSource requires a unique single file configuration that saves time and keeps the false-positives rate at less than 5%. DeepSource's auto-fix feature generates PR for the commonly occurring issues, unlike Codacy where you have to manually fix the issue. Some more advantages over Codacy are mentioned [here](https://deepsource.io/codacy-alternatives/).

2. As of now we can't move the configuration from `.deepsource.toml` to the [tool.deepsource] section. It needs to be there.

**Comment by casperdcl** [comment]
Hmm afaik a new Pythpn static analysis tool configured in `toml` outside the standard `pyproject.toml` is an anti-pattern and definitely enough of a reason to not merge this unless fixed.

**Comment by withshubh** [comment]
> Hmm afaik a new Python static analysis tool configured in `toml` outside the standard `pyproject.toml` is an anti-pattern and definitely enough of a reason to not merge this unless fixed.

Hi @casperdcl :wave: 

Since DeepSource works as an additional service (just like Codacy, etc.) that you don’t have to run yourself, we have certain restrictions (just like how you need to create workflow YAML files for GitHub Actions or Circle CI, or the codecov.yml which is already present in the repository).
The scope of what you can do is also more than one programming language: for instance, you can use DeepSource to track test coverage, detect problems in Dockerfiles, etc. in addition to detecting issues in Python. This is why we’ve taken a decision to keep the configuration independent. A number of popular open-source projects, including the likes of isort (https://github.com/pycqa/isort) use DeepSource with the configuration file as is.

**Pull request closed without merging**
