### PR TITLE
makefile

### PR DESCRIPTION
**Pull request by casperdcl**
migrated from #42

### CODE REVIEW

**Comment by lrq3000** [comment]
I wanted to make tox the default unit test when we use `python setup.py test`, but to do that, we need to add a whole Tox class inside setup.py, as described here (because else tox doesn't play nice with setup.py test):

https://testrun.org/tox/latest/example/basic.html#integration-with-setuptools-distribute-test-commands

Apart from that, the remaining issue is that I can't find a way to make `python setup.py check` run fine in tox.

**Comment by lrq3000** [comment]
Ok fixed the issue with `setup.py check`. All good now. Tell me if you want to make tox the default unittest when doing `python setup.py test` (which requires to add a Tox class in setup.py) or if we keep nose.

**Comment by lrq3000** [comment]
Here's another way to replace the makefile by setup.py:

http://www.pydanny.com/python-dot-py-tricks.html

This could do the trick, don't you think? It would work just the same as the Makefile, but without requiring to use `make`.

**Comment by casperdcl** [comment]
hmm like the link... not sure about the `python setup.py test` command, and also would prefer `subprocess` to `system` but yeah, good stuff.

**Comment by lrq3000** [comment]
Yes we can use subprocess, there's a comment at the bottom of the link where someone suggests to use subprocess, but it's a bit more cumbersome to write commands this way. We could also make a "Makefile parser", so that the Makefile could be kept and managed by setup.py instead of `make` (am I understandable or should I clarify?).

**Comment by lrq3000** [comment]
I implemented a solution inspired by the link above, but we keep using the Makefile to define aliases and commands instead of having to define them in setup.py (the conversion is automatically managed in setup.py).

Now, every `make [alias]` commands can be replaced by `python setup.py make [alias]`: the commands will be executed just the same but without requiring `make`, only native Python interpreter and libs.

If you look in the sourcecode of setup.py, you will notice that the makefile parsing functions use quite a lot of space (this basically doubled the size of setup.py), but keep in mind that this function is minimal compared to what you can find in other libraries (because I only substitute variables, I'm not trying to design a full makefile syntax parser which would be a lot longer).

BTW, I tried to use distutils.sysconfig.parse_makefile(), but it didn't work with ours (and it seems we're not the only ones to have issues with this func based on mailing lists, but anyway it was done to parse Python's makefile, not per python modules makefiles).

**Comment by lrq3000** [comment]
For my part, I'm done with this branch, except if you have any suggestion. So if it's ok for you, we can merge.

**Comment by lrq3000** [comment]
Cannot make Travis automatically check setup.py, because it seems that because of tox virtualenv, a dynamically generated setup.py is created and this is the one that gets checked instead of ours. That, or maybe it's due to a [python bug](http://bugs.python.org/issue23063). Anyway, I removed setup.py checking in Travis. We can still run it using `python setup.py make testsetup` or `tox`.

**Comment by lrq3000** [comment]
Ok I'm really done now :) You can merge whenever you want guys

**Comment by casperdcl** [comment]
Any idea what's wrong?

```sh
/tqdm$ python setup.py check --restructuredtext --strict
/usr/local/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '2.0.0.dev' to '2.0.0.dev0'
  normalized_version,
running check
warning: check: Could not finish the parsing.

error: Please correct your package.
```

**Comment by lrq3000** [comment]
How did you get this error? On travis or on your own machine?

The issue is normally with `--restructuredtext`, if you remove this argument, you won't get the error. But the error should not happen, this is a bug in distutils.

**Comment by casperdcl** [comment]
My own machine -.-

**Comment by lrq3000** [comment]
What version of Python are you using? 2.7.10 or 2.7.9?

**Comment by casperdcl** [comment]
2.7.9 with everything updated (tested on both Ubuntu 14.04 and Debian Jessie)

**Comment by lrq3000** [comment]
I guess the issue with `--restructuredtext` is fixed in Python 2.7.10. Meanwhile, just don't use this test at all or remove the conflicting argument since it's unconclusive on your machine... I don't know if we can specify a minimum python version in tox?

**Comment by casperdcl** [comment]
running the tests out-of-the-box on the default version of python on most unix installs (2.7.9) shouldn't produce an error... a work-around such as specifying minimum versions as you suggested I think is definitely needed.

However.... no way to test `rst` for pypi compliance on 2.7.9? Really?

**Comment by lrq3000** [comment]
No, unless you monkeypatch distutils from tqdm's setup.py to avoid this issue. Or maybe using docutils and pygments directly (since they are the required dependencies to run this test, but I have no idea how the test is run, didn't look at distutils sourcecode).

**Comment by lrq3000** [comment]
I updated the branch to be up-to-date with master. If you guys think the changes are OK, please merge, so that we can more easily do the maintenance task :)

**Comment by lrq3000** [comment]
Thank's @casperdcl :)

**Pull request merged**
