### PR TITLE
Copyediting for README

### PR DESCRIPTION
**Pull request by CrazyPython**

### CODE REVIEW

**Comment by lrq3000** [comment]
Thank's, tell us when you think you're done with this PR so that we can merge in.

**Comment by CrazyPython** [comment]
@lrq3000 Well then I guess I'm done now.

**Comment by CrazyPython** [comment]
@lrq3000 Wait a second - just spotted something.

**Comment by CrazyPython** [comment]
@lrq3000 should be GTG

**Comment by CrazyPython** [comment]
@coveralls why you gotta malfunction?

and why's my readme change failing Travis CI?!?!

**Comment by CrazyPython** [comment]
Coveralls is going haywire - the coveralls build is why travis CI went down.

**Comment by CrazyPython** [comment]
Ha, manually edited the "Propose change" button to not be disabled. seeing if Travis CI still has that problem...

**Comment by CrazyPython** [comment]
@lrq3000 Added an empty commit and now Travis CI automagically works again. :/

**Comment by lrq3000** [comment]
Wait wait, I'm rebasing your branch right now to clean it up, the merging seems to have failed somehow.

**Comment by casperdcl** [comment]
I already rebased and merged this yesterday...

**Comment by lrq3000** [comment]
Sorry I can't see where it was merged? That's weird. What is the commit?

**Comment by CrazyPython** [comment]
@casperdcl how are you merging invisibly?

**Comment by casperdcl** [comment]
rebased! it's in the (multiline) commit mesaages. I'll rebase squash your last commit on too I'm a few min...

**Comment by lrq3000** [comment]
@casperdcl Are you talking about [this commit](https://github.com/tqdm/tqdm/commit/c893d90768841beb4ef4d2236cfbdf7b018e0d78)?

**Comment by CrazyPython** [comment]
Is this some trick you're doing to prevent me from getting the commit credit?

<sub><sup><sub><sup>jk</sup></sub></sup></sub>

**Comment by casperdcl** [comment]
errm yes... except the diff on my local machine is showing #240 as part of it too. wth?

**Comment by lrq3000** [comment]
@CrazyPython nope that's my fault, it's the first time I did `merge --squash` manually instead of via GitHub interface, and by default it attributes the commit to the squasher (which is weird and [discussed here](http://git.661346.n2.nabble.com/Keep-original-author-with-git-merge-squash-td7625268.html)). I was going to fix this in a minute, sorry about that.

**Comment by CrazyPython** [comment]
Did anyone notice the tiny text at the bottom of my message?

**Comment by lrq3000** [comment]
That's weird @casperdcl , it seems this version of the commit wasn't pushed to the server, since the diff does not include the changes in #240.

**Comment by CrazyPython** [comment]
*groans* Bad git. Bad.

**Comment by lrq3000** [comment]
Ah no @CrazyPython, I didn't know we could write so small in Github :) But anyway I'd like to fix that. @casperdcl , how do you force push? Do you have to disable the protection from Github interface everytime?

**Comment by casperdcl** [comment]
yes, it's a different hash on my machine too. Weird. anyway maybe it's better this way if @CrazyPython is desperate to have lines attributed to him. All I need to do is leave everyrhing as is, except change the author of the last commit back to him.

**Comment by CrazyPython** [comment]
@lrq3000 A trick with `<sub><sup><sub><sup>jk</sup></sub></sup></sub>`.

**Comment by CrazyPython** [comment]
@casperdcl it's not much, just a joke :)

**Comment by lrq3000** [comment]
@CrazyPython Ah nice! Did you see [this one](https://github.com/Miserlou/Zalgo)?

**Comment by lrq3000** [comment]
About commit authorship attribution, yeah but anyway it's better to fix that so that we know how to do in the future, and it's better practice anyway.

**Comment by lrq3000** [comment]
@casperdcl how can you change the author of a commit? Remove the commit and redo it with `--author="CrazyPython"` or is there another command?

**Comment by CrazyPython** [comment]
@lrq3000 I'm gonna use that from now on whenever I want to prove a point on GitHub. You might regret this someday...

**Comment by lrq3000** [comment]
Ah lol, I should think before giving stuff next time ;)

**Comment by casperdcl** [comment]
loving the gif here https://github.com/Miserlou/Zappa

**Comment by CrazyPython** [comment]
@casperdcl soon tqdm shall take over the world!

**Comment by casperdcl** [comment]
I'm surprised and humbled by the number of times I see tqdm listed in pretty sweet package requirements/dependencies ...

**Comment by CrazyPython** [comment]
@casperdcl That's why porting to other languages = world domination.

**Comment by lrq3000** [comment]
@casperdcl Yep me too, but it's also scary because we have to make sure that our package is robust now that others are depending on it (#222) XD

**Comment by CrazyPython** [comment]
*With great power comes great irresponsibility.*

**Comment by lrq3000** [comment]
Ok so let's get serious a bit ;) @casperdcl would you like to fix the author of the copyediting commit or I do it?

**Comment by CrazyPython** [comment]
@casperdcl [If you ever feel down...](https://github.com/search?l=&q=tqdm+extension%3Atxt&ref=advsearch&type=Code&utf8=✓)

**Comment by lrq3000** [comment]
@CrazyPython Oh wow, never thought of doing that. And that's only for github hosted projects, there are more outside.

**Comment by lrq3000** [comment]
Even for sample code of a book: https://github.com/trenton3983/Fluent_Python

**Comment by CrazyPython** [comment]
> CrazyPython committed with casperdcl an hour ago

I HAVE ACCESS! MUAHAHAHA!

**Comment by CrazyPython** [comment]
I found a hidden little GitHub feature: https://github.com/tqdm/tqdm/branches

**Comment by lrq3000** [comment]
@CrazyPython Nice finding, might be useful to clean up our branches!

@casperdcl Thank you for fixing authorship :) Out of curiosity, how did you do it? `commit --author="CrazyPython"` ?

**Comment by casperdcl** [comment]
That is... a lot of users. First reaction: pleasant shock. Second reaction: puzzled as to why first reaction was surprised. This is still less than what we're aiming for ;)

**Comment by casperdcl** [comment]
Since when was branches hidden? Next you'll tell me you've never seen the punch card, network, or contributors pages

**Comment by CrazyPython** [comment]
@casperdcl Oh, I've seen those - just how do you find it without entering the URL manually?

**Comment by casperdcl** [comment]
Drat it. tests. Finally looked at Travis. coverage submission has been failing specifically on py34. grrr

**Comment by lrq3000** [comment]
@casperdcl It's probably coveralls that's still failing. @CrazyPython reported the issue and they said they are fixing the issue.

**Comment by lrq3000** [comment]
@CrazyPython Found how to show branches from interface: Code > Branches in the submenu, just at the right of "commits". That's on the new interface only, it wasn't there before.

**Comment by lrq3000** [comment]
@casperdcl About the number of users, remember it's only projects hosted on github, and projects that were published. I can bet there are a lot of in-house ipython notebooks and scripts using tqdm that are not published.

**Comment by CrazyPython** [comment]
@casperdcl In addition to what @lrq3000 said, there are 11k projects that aren't big enough to have a requirements.txt that use tqdm.

**Pull request closed without merging**
