### PR TITLE
CLI pipes

### PR DESCRIPTION
**Pull request by casperdcl**
attempt to clean CLI internals for all platforms
- [x] py2-win
- [x] py3-win
- [x] py2-nix (travis)
- [ ] py3-nix (travis)

### CODE REVIEW

**Comment by casperdcl** [comment]
Any ideas why this fails in py3 linux?

**Comment by lrq3000** [comment]
It seems there is a problem with the matching of `RE_TQDM_OUT` under Python3. So I guess Python3 changes something in the handling of the CLI that makes the output a bit different, and the RE doesn't match.
But I can't dig deeper as I can't test myself, sorry...

**Comment by lrq3000** [comment]
OR if it works on your local Py3 install and not on Travis Py3, then maybe you are stumbling on a similar issue I had in the past, with Travis having a weird configuration of the terminal for Py3. I remember I had to fix a regex because of that, but I can't remember which one nor how...

**Comment by lrq3000** [comment]
I think the weird Py3 bug and regex fix I did was about this issue:
https://github.com/tqdm/tqdm/pull/87#issuecomment-170300713

But I don't know why I didn't describe the fix I did, so we would have to dig in the commits log to find out, but it's not guaranteed at all that we are meeting the same issue here... But this confirms that Travis bugs with Py3 are not uncommon.

**Comment by lrq3000** [comment]
Did you try to make a debug commit to trigger Travis with a print of the matching of `RE_TQDM_OUT`? I'm pretty sure this will help understanding what's happening.

**Comment by lrq3000** [comment]
Because it seems it's only a missing '\n' at the beginning of res_stripped[-1], which is:

```
'CONTRIBUTE  images   logo.png  MANIFEST.in  setup.cfg  tox.ini\ttqdm.egg-info\nexamples    LICENCE  Makefile  README.rst   setup.py   tqdm\n\n'
```
So there's no `\n` at the beginning. Maybe this was stripped by the generating command because of a different behavior in Py3 (I didn't read the test yet)?

**Comment by lrq3000** [comment]
Ok so I did the debug commit, here is the expected result on Py2-linux:

```res_stripped = [u'', u'', u'\nCONTRIBUTE  images   logo.png  MANIFEST.in  setup.cfg  tox.ini\ttqdm.egg-info\nexamples    LICENCE  Makefile  README.rst   setup.py   tqdm\n']```

And here is the result on Py3-linux:

```res_stripped = ['', '', 'CONTRIBUTE  images   logo.png  MANIFEST.in  setup.cfg  tox.ini\ttqdm.egg-info\nexamples    LICENCE  Makefile  README.rst   setup.py   tqdm\n\n']```

So there is something wrong either with the regex or some command is not returning what is expected.

**Comment by lrq3000** [comment]
More debugging:

```
def test_main():
...
    print(res_split)
    print(res)
    print(ls_out)
```

Py2-linux:
```
    print([u'', u'', u'\nCONTRIBUTE  images   logo.png  MANIFEST.in  setup.cfg  tox.ini\ttqdm.egg-info\nexamples    LICENCE  Makefile  README.rst   setup.py   tqdm\n'])
    print(u'\r0it [00:00, ?it/s]\r2it [00:00, 29852.70it/s]\nCONTRIBUTE  images   logo.png  MANIFEST.in  setup.cfg  tox.ini\ttqdm.egg-info\nexamples    LICENCE  Makefile  README.rst   setup.py   tqdm\n')
    print(u'CONTRIBUTE  images   logo.png  MANIFEST.in  setup.cfg  tox.ini\ttqdm.egg-info\nexamples    LICENCE  Makefile  README.rst   setup.py   tqdm\n')
```

Py3-linux:
```
    print(['', '', 'CONTRIBUTE  images   logo.png  MANIFEST.in  setup.cfg  tox.ini\ttqdm.egg-info\nexamples    LICENCE  Makefile  README.rst   setup.py   tqdm\n\n'])
    print('\r0it [00:00, ?it/s]\r2it [00:00, 9372.75it/s]CONTRIBUTE  images   logo.png  MANIFEST.in  setup.cfg  tox.ini\ttqdm.egg-info\nexamples    LICENCE  Makefile  README.rst   setup.py   tqdm\n\n')
    print('CONTRIBUTE  images   logo.png  MANIFEST.in  setup.cfg  tox.ini\ttqdm.egg-info\nexamples    LICENCE  Makefile  README.rst   setup.py   tqdm\n')
```

So it's not the regex, it's the following command that does not return the same output depending if it's Py2 or Py3:
```
    res = _sh('python', '-c', r'import sys; sys.argv = ["", "--delim", "\\t"];'
                              ' from tqdm import main; main()',
              stdin=ls.stdout,
              stderr=subprocess.STDOUT)
```

**Comment by lrq3000** [comment]
Actually I just tested on Windows and the same problem happens: on Py2, there will be a newline return between the progress bar and the list of files, but on Py3 there's not. So it's not a bug of Travis, but a different behavior from Py2 to Py3. I don't know if it's tqdm or a native Python library that has changed.

**Comment by lrq3000** [comment]
I tested again, and actually there is never a newline return between the progress bar and the files listing, neither on Py2 nor Py3 on Windows. So in fact Py2-linux is the exception since there is a newline return there where it should not.

Here is my output on Py2-win:
```
    print([u'', u'CONTRIBUTE   Makefile\t images\t\t\tsetup.cfg  tqdm\r\nLICENCE
      README.rst  logo.png\t\tsetup.py\r\nMANIFEST.in  examples\t python_test_py
py3.bat\ttox.ini\r\n', u'\r\n'])
    print(u'\r0it [00:00, ?it/s]CONTRIBUTE   Makefile\t images\t\t\tsetup.cfg  t
qdm\r\nLICENCE      README.rst  logo.png\t\tsetup.py\r\nMANIFEST.in  examples\t
python_test_pypy3.bat\ttox.ini\r\n\r9it [00:00, 8998.51it/s]\r\n')
    print(u'CONTRIBUTE   Makefile\t images\t\t\tsetup.cfg  tqdm\nLICENCE      RE
ADME.rst  logo.png\t\tsetup.py\nMANIFEST.in  examples\t python_test_pypy3.bat\tt
ox.ini\n')
```

And it's about the same on Py3. Notice the `\r\n\r9it [00:00, 8998.51it/s]\r\n` at the end and the double `\n\n` on Py3-linux. My guess is that the result gets **asynchronously** received, and this creates a racing condition, with the result being printed after the bar but before the bar prints a newline return.

But it's up to you to see more in-depth, I don't understand the code in `_main.py` enough to fix it!

**Comment by lrq3000** [comment]
PS: if you could add some comments it would be easier to maintain this in the future I think.

**Comment by casperdcl** [comment]
outdated & fixed

**Pull request closed without merging**
