### PR TITLE
Better GitHub contributing integrations

### LINKED ISSUE #309: known-issues
Discussion continued from issues listed below. The appropriate section would be https://github.com/tqdm/tqdm/#help, possibly in a sub-section "known issues" shall we make a list here for now?

Lack of carriage return and/or up control characters:
- PyCharm #307 #208 #203 
- IDLE #191 
- ConEmu #254

Abstraction:
- zip #256 (fix by replacing `tqdm(zip(a, b))` with `zip(tqdm(a), b)` or even `zip(tqdm(a), tqdm(b))`)
- enumerate #157 (incl. numpy versions. `len` is hidden. fix by replacing `tqdm(enumerate(a))` with `enumerate(tqdm(a))`)

### PR DESCRIPTION
**Pull request by casperdcl**
Fixes #309: Discussion continued from issues listed below. The appropriate section would be https://github.com/tqdm/tqdm/#help, possibly in a sub-section "known issues" shall we make a list here for now?

## Lack of carriage return and/or up control characters
- [x] PyCharm #307 #208 #203 
- [x] IDLE #191 
- [x] ConEmu #254

## Abstraction
- [x] zip #256 (fix by replacing `tqdm(zip(a, b))` with `zip(tqdm(a), b)` or even `zip(tqdm(a), tqdm(b))`)
- [x] enumerate #157 (incl. numpy versions. `len` is hidden. fix by replacing `tqdm(enumerate(a))` with `enumerate(tqdm(a))`)

## Other
- [x] `.github/` folder with templates

### CODE REVIEW

**Comment by lrq3000** [comment]
Just a question: why did you move CONTRIBUTE to the .github folder? Will this be also displayed somewhere on github?

**Comment by casperdcl** [comment]
Thanks Stephen. I moved it simply because github's own help page about the .github folder did this. I don't really mind, I think github also looks in the root directory of the repo for files (hence it finds things like readme.rst) so I could move it back. Don't think it displays anywhere special yet. The templates however will display when opening new issues/PRs.

**Comment by casperdcl** [comment]
/edit if you for example attempt to open a mew issue, github will display a link to the contributing file now.

**Comment by lrq3000** [comment]
Ahhh that's great! Thank you Casper, it's perfect :)

2017-01-06 0:12 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Pull request merged**
