### PR TITLE
CLI --bytes

### PR DESCRIPTION
**Pull request by casperdcl**
~~work in progress~~ done
- [x] support counting bytes
- [x] docs
- [x] tests

### CODE REVIEW

**Comment by lrq3000** [comment]
Great work @casperdcl :+1:

But you should really comment main.py someday because I can't understand everything, for example I don't know why you are using your own regexp RE_SHLEX instead of the python lib shlex, but I guess you already tried it.

**Comment by lrq3000** [comment]
What I mean is that I cannot help you mantain this part of tqdm currently, comments would really be helpful to me :(

**Comment by casperdcl** [comment]
Ah there were reasons. I recall forgetting, then remembering, then forgetting. It's similar to why docopt doesn't use shlex either. much more control. I essentially parse option names and values simultaneously, then use the `cast` function to extract the appropriate type, which in term is extracted from my strict docstring format of 8 spaces + kwarg + 2 space + colon + type + ... + "[default: ...]"

**Comment by lrq3000** [comment]
Ok thank's for the explanation, but I also don't understand the rest of the
code XD If you can, please add some comments to help me understand the
general outline, I will be able to contribute (this is I think a killer
feature of tqdm, I'm sure there's a lot to be expanded on this side to make
it even more useful).

2016-10-29 23:32 GMT+02:00 Casper da Costa-Luis <notifications@github.com>:

**Pull request merged**
